# Apach Spark 
## Um pandas tunado com cluster e distribuição por scala (ideal para grandes volumes)

### Repo da aula onde estão os arquivos CSV
[https://github.com/torneseumprogramador/python-data-science-spark](https://github.com/torneseumprogramador/python-data-science-spark)

In [ ]:
!java -version

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

In [ ]:
!python --version

Python 3.8.10

In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 KB 23.7 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824025 sha256=c5068eba55da95b803f56ec1dc572d92376ecf0b7e854d87b8bfbd7aab355f22
  Stored in directory: /root/.cache/pip/wheels/b1/59/a0/a1a0624b5e865fd389919c1a10f53aec9b12195d6747710baf
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.2

In [ ]:
!wget -q https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz

In [ ]:
!tar -xvzf spark-3.3.2-bin-hadoop3.tgz

spark-3.3.2-bin-hadoop3/
spark-3.3.2-bin-hadoop3/LICENSE
spark-3.3.2-bin-hadoop3/NOTICE
spark-3.3.2-bin-hadoop3/R/
spark-3.3.2-bin-hadoop3/R/lib/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/DESCRIPTION
spark-3.3.2-bin-hadoop3/R/lib/SparkR/INDEX
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/Rd.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/features.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/hsearch.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/links.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/nsInfo.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/package.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/vignette.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/NAMESPACE
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR.rdb
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR.rdx
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/index.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.Rmd
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/AnIndex
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/SparkR.rdb
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/SparkR.rdx
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/aliases.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/paths.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/00Index.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/R.css
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/general.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/shell.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/testthat/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/daemon.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/worker.R
spark-3.3.2-bin-hadoop3/R/lib/sparkr.zip
spark-3.3.2-bin-hadoop3/README.md
spark-3.3.2-bin-hadoop3/RELEASE
spark-3.3.2-bin-hadoop3/bin/
spark-3.3.2-bin-hadoop3/bin/beeline
spark-3.3.2-bin-hadoop3/bin/beeline.cmd
spark-3.3.2-bin-hadoop3/bin/docker-image-tool.sh
spark-3.3.2-bin-hadoop3/bin/find-spark-home
spark-3.3.2-bin-hadoop3/bin/find-spark-home.cmd
spark-3.3.2-bin-hadoop3/bin/load-spark-env.cmd
spark-3.3.2-bin-hadoop3/bin/load-spark-env.sh
spark-3.3.2-bin-hadoop3/bin/pyspark
spark-3.3.2-bin-hadoop3/bin/pyspark.cmd
spark-3.3.2-bin-hadoop3/bin/pyspark2.cmd
spark-3.3.2-bin-hadoop3/bin/run-example
spark-3.3.2-bin-hadoop3/bin/run-example.cmd
spark-3.3.2-bin-hadoop3/bin/spark-class
spark-3.3.2-bin-hadoop3/bin/spark-class.cmd
spark-3.3.2-bin-hadoop3/bin/spark-class2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-shell
spark-3.3.2-bin-hadoop3/bin/spark-shell.cmd
spark-3.3.2-bin-hadoop3/bin/spark-shell2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-sql
spark-3.3.2-bin-hadoop3/bin/spark-sql.cmd
spark-3.3.2-bin-hadoop3/bin/spark-sql2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-submit
spark-3.3.2-bin-hadoop3/bin/spark-submit.cmd
spark-3.3.2-bin-hadoop3/bin/spark-submit2.cmd
spark-3.3.2-bin-hadoop3/bin/sparkR
spark-3.3.2-bin-hadoop3/bin/sparkR.cmd
spark-3.3.2-bin-hadoop3/bin/sparkR2.cmd
spark-3.3.2-bin-hadoop3/conf/
spark-3.3.2-bin-hadoop3/conf/fairscheduler.xml.template
spark-3.3.2-bin-hadoop3/conf/log4j2.properties.template
spark-3.3.2-bin-hadoop3/conf/metrics.properties.template
spark-3.3.2-bin-hadoop3/conf/spark-defaults.conf.template
spark-3.3.2-bin-hadoop3/conf/spark-env.sh.template
spark-3.3.2-bin-hadoop3/conf/workers.template
spark-3.3.2-bin-hadoop3/data/
spark-3.3.2-bin-hadoop3/data/graphx/
spark-3.3.2-bin-hadoop3/data/graphx/followers.txt
spark-3.3.2-bin-hadoop3/data/graphx/users.txt
spark-3.3.2-bin-hadoop3/data/mllib/
spark-3.3.2-bin-hadoop3/data/mllib/als/
spark-3.3.2-bin-hadoop3/data/mllib/als/sample_movielens_ratings.txt
spark-3.3.2-bin-hadoop3/data/mllib/als/test.data
spark-3.3.2-bin-hadoop3/data/mllib/gmm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/
spark-3.3.2-bin-hadoop3/data/mllib/images/license.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/54893.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/not-image.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/license.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.3.2-bin-hadoop3/data/mllib/kmeans_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/pagerank_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/pic_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/ridge-data/
spark-3.3.2-bin-hadoop3/data/mllib/ridge-data/lpsa.data
spark-3.3.2-bin-hadoop3/data/mllib/sample_binary_classification_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_fpgrowth.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_kmeans_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_lda_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_lda_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_linear_regression_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_movielens_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_multiclass_classification_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_svm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/streaming_kmeans_data_test.txt
spark-3.3.2-bin-hadoop3/data/streaming/
spark-3.3.2-bin-hadoop3/data/streaming/AFINN-111.txt
spark-3.3.2-bin-hadoop3/examples/
spark-3.3.2-bin-hadoop3/examples/jars/
spark-3.3.2-bin-hadoop3/examples/jars/scopt_2.12-3.7.1.jar
spark-3.3.2-bin-hadoop3/examples/jars/spark-examples_2.12-3.3.2.jar
spark-3.3.2-bin-hadoop3/examples/src/
spark-3.3.2-bin-hadoop3/examples/src/main/
spark-3.3.2-bin-hadoop3/examples/src/main/java/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRandomForestClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRandomForestRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRankingMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRecommendationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSVDExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSVMWithSGDExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSimpleFPGrowth.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaStratifiedSamplingExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaStreamingTestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaSummaryStatisticsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaSQLDataSourceExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaSparkSQLExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaUserDefinedScalar.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/sql/JavaUserDefinedTypedAggregation.java

In [ ]:
!pip install -q findspark

Descobrir caminho do java

In [ ]:
!ls /usr/lib/jvm/

default-java  java-1.11.0-openjdk-amd64  java-11-openjdk-amd64

Descobrir caminho spark hadoop

In [ ]:
!ls spark-3.3.1-bin-hadoop3

bin   data	jars	    LICENSE   NOTICE  R		 RELEASE  yarn
conf  examples	kubernetes  licenses  python  README.md  sbin

In [ ]:
!pwd

/content

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.2-bin-hadoop3"
import findspark
findspark.init()

In [ ]:
# criando um data frame

from pyspark.sql import SparkSession

# Cria um DataFrame de exemplo
spark = SparkSession.builder.appName("rename_column").getOrCreate()
data = [("João", 25), ("Maria", 30), ("José", 40)]
df = spark.createDataFrame(data, ["nome", "idade"])

df.show()

+-----+-----+
| nome|idade|
+-----+-----+
| João|   25|
|Maria|   30|
| José|   40|
+-----+-----+

In [ ]:
from pyspark.sql import SparkSession

# Cria ou/e inicia uma sessão spark
spark = SparkSession.builder.master("local[*]").appName("Read CSV").getOrCreate() # master("local[*]") - indica que quero utilizar todas as CPU's do meu spark

# ===== caso tenha um cluster spark configurado =======
# spark = SparkSession.builder.appName("MyApp").master(f"spark://172.111.111.11:7077").getOrCreate() 

# Le arquivo csv
df = spark.read.csv("/content/csv/clientes.csv", header=True, inferSchema=True)
# df = spark.read.csv("/content/csv/*.csv", header=True, inferSchema=True) para ler multiplos arquivos

# Mostra dataframe
df.show()

+---+--------------+--------------+--------------------+--------------------+
| id|          nome|      telefone|            endereco|               email|
+---+--------------+--------------+--------------------+--------------------+
|  1|    João Silva|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|  2|Maria Oliveira|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|  3|   Pedro Sousa|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|  4|    Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|  5|     Ana Paula|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
+---+--------------+--------------+--------------------+--------------------+

In [ ]:
# verifica sessão spark aberta e mostra URL do spark web
spark

In [ ]:
# criar um dataframe
data = [('Danilo', 'danilo@teste.com', '11 1111-1111'), ('Leandro', 'leo@teste.com', '11 1111-1111')] # lista de tuple
colunas = ['Nome', 'Email', 'Telefone'] # array

df = spark.createDataFrame(data, colunas)
df

DataFrame[Nome: string, Email: string, Telefone: string]

In [ ]:
df.show()

+-------+----------------+------------+
|   Nome|           Email|    Telefone|
+-------+----------------+------------+
| Danilo|danilo@teste.com|11 1111-1111|
|Leandro|   leo@teste.com|11 1111-1111|
+-------+----------------+------------+

In [ ]:
df.toPandas() # mostra as informações como no pandas

      Nome             Email      Telefone
0   Danilo  danilo@teste.com  11 1111-1111
1  Leandro     leo@teste.com  11 1111-1111

In [ ]:
# convertendo tipo colunas 

from pyspark.sql import SparkSession
from pyspark.sql.functions import to_timestamp, col

# Criando uma SparkSession
spark = SparkSession.builder.appName('ConvertDataTypes').getOrCreate()

# criar um dataframe
data = [('1', '33.33', '1990-12-09 22:54:00', 'True')] # lista de tuple
colunas = ['id', 'valor_faturamento', 'data_faturamento', 'ativo'] # array

df = spark.createDataFrame(data, colunas)

# Visualizando o DataFrame com os novos tipos de dados
df.printSchema()

# Visualizando o DataFrame original
df.show()

# Alterando tipo de colunas
df = df.withColumn('id', df['id'].cast('integer'))
df = df.withColumn('valor_faturamento', df['valor_faturamento'].cast('float'))
df = df.withColumn('data_faturamento', to_timestamp(col('data_faturamento'), 'yyyy-MM-dd HH:mm:ss'))
df = df.withColumn('ativo', df['ativo'].cast('boolean'))

# Visualizando o DataFrame com os novos tipos de dados
df.printSchema()
df.show()

root
 |-- id: string (nullable = true)
 |-- valor_faturamento: string (nullable = true)
 |-- data_faturamento: string (nullable = true)
 |-- ativo: string (nullable = true)

+---+-----------------+-------------------+-----+
| id|valor_faturamento|   data_faturamento|ativo|
+---+-----------------+-------------------+-----+
|  1|            33.33|1990-12-09 22:54:00| True|
+---+-----------------+-------------------+-----+

root
 |-- id: integer (nullable = true)
 |-- valor_faturamento: float (nullable = true)
 |-- data_faturamento: timestamp (nullable = true)
 |-- ativo: boolean (nullable = true)

+---+-----------------+-------------------+-----+
| id|valor_faturamento|   data_faturamento|ativo|
+---+-----------------+-------------------+-----+
|  1|            33.33|1990-12-09 22:54:00| true|
+---+-----------------+-------------------+-----+

In [ ]:
# exemplo de conversão com dados do spark

from pyspark.sql import SparkSession
from pyspark.sql.functions import to_timestamp, col
from pyspark.sql.types import IntegerType, DoubleType, BooleanType, TimestampType

# Criando uma SparkSession
spark = SparkSession.builder.appName('ConvertDataTypes').getOrCreate()

# Criando um dataframe
data = [('1', '33.33', '1990-12-09 22:54:00', 'True')] # lista de tuple
colunas = ['id', 'valor_faturamento', 'data_faturamento', 'ativo'] # array

df = spark.createDataFrame(data, colunas)

# Visualizando o DataFrame original
df.printSchema()
df.show()

# Convertendo os tipos de colunas
df = df.withColumn('id', df['id'].cast(IntegerType()))
df = df.withColumn('valor_faturamento', df['valor_faturamento'].cast(DoubleType()))
df = df.withColumn('data_faturamento', to_timestamp(col('data_faturamento'), 'yyyy-MM-dd HH:mm:ss').cast(TimestampType()))
df = df.withColumn('ativo', df['ativo'].cast(BooleanType()))

# Visualizando o DataFrame com os novos tipos de dados
df.printSchema()
df.show()

root
 |-- id: string (nullable = true)
 |-- valor_faturamento: string (nullable = true)
 |-- data_faturamento: string (nullable = true)
 |-- ativo: string (nullable = true)

+---+-----------------+-------------------+-----+
| id|valor_faturamento|   data_faturamento|ativo|
+---+-----------------+-------------------+-----+
|  1|            33.33|1990-12-09 22:54:00| True|
+---+-----------------+-------------------+-----+

root
 |-- id: integer (nullable = true)
 |-- valor_faturamento: double (nullable = true)
 |-- data_faturamento: timestamp (nullable = true)
 |-- ativo: boolean (nullable = true)

+---+-----------------+-------------------+-----+
| id|valor_faturamento|   data_faturamento|ativo|
+---+-----------------+-------------------+-----+
|  1|            33.33|1990-12-09 22:54:00| true|
+---+-----------------+-------------------+-----+

Agora vou ler todos os arquivos da minha pasta CSV

In [ ]:
path = '/content/csv_particionado'
# path = '/content/csv_particionado/*000.csv' # para ler arquvivos com um padrão *000.csv
# df = spark.read.csv("path1,path2,path3") # para ler por vários paths

clientes = spark.read.csv(path, sep=",", header=False, inferSchema=True)
clientes

DataFrame[_c0: string, _c1: string, _c2: string, _c3: string]

In [ ]:
clientes.count() # mostra a quantidade de linhas de arquivos

28180

In [ ]:
clientes.limit(3).show() # mostra os primeiros 3 registros do meu arquivo

+-----------+--------------+--------------------+--------------------+
|        _c0|           _c1|                 _c2|                 _c3|
+-----------+--------------+--------------------+--------------------+
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
+-----------+--------------+--------------------+--------------------+

In [ ]:
clientes.show() # mostra as 20 primeiras linhas de todos os arquivos separados carregados em somente um data frame, arquivos com campos diferentes não serão impostados

+-----------+--------------+--------------------+--------------------+
|        _c0|           _c1|                 _c2|                 _c3|
+-----------+--------------+--------------------+--------------------+
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
+-----------+--------------+--------------------+--------------------+
only showing top 20 rows

In [ ]:
cabecalho = ['Nome', 'Telefone', 'Endereco', 'Email']

In [ ]:
for item in enumerate(cabecalho):
  print(item)

(0, 'Nome')
(1, 'Telefone')
(2, 'Endereco')
(3, 'Email')

In [ ]:
for index,nomeColuna in enumerate(cabecalho):
        clientes = clientes.withColumnRenamed(f"_c{index}", nomeColuna)

clientes.columns

['Nome', 'Telefone', 'Endereco', 'Email']

In [ ]:
clientes.show()

+-----------+--------------+--------------------+--------------------+
|       Nome|      Telefone|            Endereco|               Email|
+-----------+--------------+--------------------+--------------------+
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
+-----------+--------------+--------------------+--------------------+
only showing top 20 rows

In [ ]:
clientes.show(10) # mostra somente 10 linhas no show

+-----------+--------------+--------------------+--------------------+
|       Nome|      Telefone|            Endereco|               Email|
+-----------+--------------+--------------------+--------------------+
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
|    Ludmila|(11) 1234-5678| Rua ABC - 123 - ...| joao.silva@email...|
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - ...| maria.oliveira@e...|
|     Otávio|(11) 3456-7890| Rua GHI - 789 - ...| pedro.sousa@emai...|
|      Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|      Olavo|(21) 5678-9012| Rua PQR - 753 - ...| ana.paula@email.com|
+-----------+--------------+--------------------+--------------------+
only showing top 10 rows

In [ ]:
clientes.show(10, False) # mostra somente 10 linhas no show, porém com todos os valores mostrando sem ...

+-----------+--------------+-------------------------------------------------+-------------------------+
|Nome       |Telefone      |Endereco                                         |Email                    |
+-----------+--------------+-------------------------------------------------+-------------------------+
|Ludmila    |(11) 1234-5678| Rua ABC - 123 - Bairro XYZ - São Paulo - SP     | joao.silva@email.com    |
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - Bairro UVW - São Paulo - SP     | maria.oliveira@email.com|
|Otávio     |(11) 3456-7890| Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ| pedro.sousa@email.com   |
|Lobão      |(21) 4567-8901| Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ| lucas.lima@email.com    |
|Olavo      |(21) 5678-9012| Rua PQR - 753 - Bairro STU - Belo Horizonte - MG| ana.paula@email.com     |
|Ludmila    |(11) 1234-5678| Rua ABC - 123 - Bairro XYZ - São Paulo - SP     | joao.silva@email.com    |
|Jarteclenio|(11) 2345-6789| Rua DEF - 456 - Bairro UVW - São Paulo - SP     | maria.oliveira@email.com|
|Otávio     |(11) 3456-7890| Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ| pedro.sousa@email.com   |
|Lobão      |(21) 4567-8901| Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ| lucas.lima@email.com    |
|Olavo      |(21) 5678-9012| Rua PQR - 753 - Bairro STU - Belo Horizonte - MG| ana.paula@email.com     |
+-----------+--------------+-------------------------------------------------+-------------------------+
only showing top 10 rows

In [ ]:
clientes.show(n=20,truncate=20,vertical=True) # mostrando de forma vertical e truncando dados com 20 caracteres

-RECORD 0------------------------
 Nome     | Ludmila
 Telefone | (11) 1234-5678
 Endereco |  Rua ABC - 123 - ...
 Email    |  joao.silva@email...
-RECORD 1------------------------
 Nome     | Jarteclenio
 Telefone | (11) 2345-6789
 Endereco |  Rua DEF - 456 - ...
 Email    |  maria.oliveira@e...
-RECORD 2------------------------
 Nome     | Otávio
 Telefone | (11) 3456-7890
 Endereco |  Rua GHI - 789 - ...
 Email    |  pedro.sousa@emai...
-RECORD 3------------------------
 Nome     | Lobão
 Telefone | (21) 4567-8901
 Endereco |  Rua JKL - 159 - ...
 Email    |  lucas.lima@email...
-RECORD 4------------------------
 Nome     | Olavo
 Telefone | (21) 5678-9012
 Endereco |  Rua PQR - 753 - ...
 Email    |  ana.paula@email.com
-RECORD 5------------------------
 Nome     | Ludmila
 Telefone | (11) 1234-5678
 Endereco |  Rua ABC - 123 - ...
 Email    |  joao.silva@email...
-RECORD 6------------------------
 Nome     | Jarteclenio
 Telefone | (11) 2345-6789
 Endereco |  Rua DEF - 456 - ...
 Email    |  maria.oliveira@e...
-RECORD 7------------------------
 Nome     | Otávio
 Telefone | (11) 3456-7890
 Endereco |  Rua GHI - 789 - ...
 Email    |  pedro.sousa@emai...
-RECORD 8------------------------
 Nome     | Lobão
 Telefone | (21) 4567-8901
 Endereco |  Rua JKL - 159 - ...
 Email    |  lucas.lima@email...
-RECORD 9------------------------
 Nome     | Olavo
 Telefone | (21) 5678-9012
 Endereco |  Rua PQR - 753 - ...
 Email    |  ana.paula@email.com
-RECORD 10-----------------------
 Nome     | Ludmila
 Telefone | (11) 1234-5678
 Endereco |  Rua ABC - 123 - ...
 Email    |  joao.silva@email...
-RECORD 11-----------------------
 Nome     | Jarteclenio
 Telefone | (11) 2345-6789
 Endereco |  Rua DEF - 456 - ...
 Email    |  maria.oliveira@e...
-RECORD 12-----------------------
 Nome     | Otávio
 Telefone | (11) 3456-7890
 Endereco |  Rua GHI - 789 - ...
 Email    |  pedro.sousa@emai...
-RECORD 13-----------------------
 Nome     | Lobão
 Telefone | (21) 4567-8901
 Endereco |  Rua JKL - 159 - ...
 Email    |  lucas.lima@email...
-RECORD 14-----------------------
 Nome     | Olavo
 Telefone | (21) 5678-9012
 Endereco |  Rua PQR - 753 - ...
 Email    |  ana.paula@email.com
-RECORD 15-----------------------
 Nome     | Ludmila
 Telefone | (11) 1234-5678
 Endereco |  Rua ABC - 123 - ...
 Email    |  joao.silva@email...
-RECORD 16-----------------------
 Nome     | Jarteclenio
 Telefone | (11) 2345-6789
 Endereco |  Rua DEF - 456 - ...
 Email    |  maria.oliveira@e...
-RECORD 17-----------------------
 Nome     | Otávio
 Telefone | (11) 3456-7890
 Endereco |  Rua GHI - 789 - ...
 Email    |  pedro.sousa@emai...
-RECORD 18-----------------------
 Nome     | Lobão
 Telefone | (21) 4567-8901
 Endereco |  Rua JKL - 159 - ...
 Email    |  lucas.lima@email...
-RECORD 19-----------------------
 Nome     | Olavo
 Telefone | (21) 5678-9012
 Endereco |  Rua PQR - 753 - ...
 Email    |  ana.paula@email.com
only showing top 20 rows

In [ ]:
clientes.head(1) # retorna a primera linha com o header, um array de tuple

[Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com')]

In [ ]:
type(clientes.head(1)) # retorna a primera linha com o header, um array de pyspark.sql.types.Row

list

In [ ]:
type(clientes.head(1)[0]) # tipo item 1 do array de pyspark.sql.types.Row

pyspark.sql.types.Row

In [ ]:
clientes.head(1)[0] # item 1 do array de pyspark.sql.types.Row

Row(_c0='Ludmila', _c1='(11) 1234-5678', _c2=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', _c3=' joao.silva@email.com')

In [ ]:
clientes.head(1)[0]["Nome"] # nome do item 1

'Ludmila'

In [ ]:
clientes.first() # retorna o primeiro item

Row(_c0='Ludmila', _c1='(11) 1234-5678', _c2=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', _c3=' joao.silva@email.com')

In [ ]:
clientes.collect() # retorna a coleção inteira de dados em formato array

[Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lobão', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Olavo', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com'),
 Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),

In [ ]:
clientes.take(3) # retorna a coleção inteira top 3 de dados em formato array

[Row(Nome='Ludmila', Telefone='(11) 1234-5678', Endereco=' Rua ABC - 123 - Bairro XYZ - São Paulo - SP', Email=' joao.silva@email.com'),
 Row(Nome='Jarteclenio', Telefone='(11) 2345-6789', Endereco=' Rua DEF - 456 - Bairro UVW - São Paulo - SP', Email=' maria.oliveira@email.com'),
 Row(Nome='Otávio', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com')]

In [ ]:
clientes.tail(3) # retorna as ultimas 3 linhas

[Row(Nome='Pedro Sousa', Telefone='(11) 3456-7890', Endereco=' Rua GHI - 789 - Bairro RST - Rio de Janeiro - RJ', Email=' pedro.sousa@email.com'),
 Row(Nome='Lucas Lima', Telefone='(21) 4567-8901', Endereco=' Rua JKL - 159 - Bairro MNO - Rio de Janeiro - RJ', Email=' lucas.lima@email.com'),
 Row(Nome='Ana Paula', Telefone='(21) 5678-9012', Endereco=' Rua PQR - 753 - Bairro STU - Belo Horizonte - MG', Email=' ana.paula@email.com')]

In [ ]:
clientes.printSchema() # mostra o esquema o dataframe

root
 |-- Nome: string (nullable = true)
 |-- Telefone: string (nullable = true)
 |-- Endereco: string (nullable = true)
 |-- Email: string (nullable = true)

In [ ]:
clientes.write.csv("/content/dataframe.csv", header=True)

In [ ]:
clientes.write.json("/content/dataframe.json")

In [ ]:
# exemplo para salvar arquivo csv, json, parquet

clientes.write.csv('/caminho/do/arquivo.csv', header=True, sep=',')
clientes.write.json('/caminho/do/arquivo.json')
clientes.write.parquet('/caminho/do/arquivo.parquet')

# coalesce(1) para criar somente um arquivo, ou seja uma partição
clientes.coalesce(1).write.csv(
    path='/content/drive/MyDrive/curso-spark/empresas/csv-unico',
    mode='overwrite',
    sep=';',
    header=True
)

In [ ]:
pedidos_df = spark.read.csv("/content/csv/pedidos.csv", header=True, inferSchema=False)
pedidos_df.show()
pedidos_df.printSchema() # mostra o esquema o dataframe um com data

+---+----------+-----------+----------+
| id|cliente_id|valor_total|      data|
+---+----------+-----------+----------+
|  1|         1|      20.20|2023-02-07|
|  2|         2|      21.40|2022-12-07|
|  3|         3|      32.50|2020-05-01|
|  4|         4|      11.13|2023-02-12|
|  5|         5|      22.45|2023-07-08|
|  6|         1|     100.80|2023-02-02|
|  7|         2|      24.60|2021-05-07|
|  8|         3|      11.20|2023-01-22|
|  9|         4|      35.00|2023-02-25|
| 10|         5|      45.80|2023-01-11|
+---+----------+-----------+----------+

root
 |-- id: string (nullable = true)
 |-- cliente_id: string (nullable = true)
 |-- valor_total: string (nullable = true)
 |-- data: string (nullable = true)

In [ ]:
pedidos_df = spark.read.csv("/content/csv/pedidos.csv", header=True, inferSchema=True)
pedidos_df.show()
pedidos_df.printSchema() # mostra o esquema o dataframe um com data

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  1|         1|       20.2|2023-02-07 00:00:00|
|  2|         2|       21.4|2022-12-07 00:00:00|
|  3|         3|       32.5|2020-05-01 00:00:00|
|  4|         4|      11.13|2023-02-12 00:00:00|
|  5|         5|      22.45|2023-07-08 00:00:00|
|  6|         1|      100.8|2023-02-02 00:00:00|
|  7|         2|       24.6|2021-05-07 00:00:00|
|  8|         3|       11.2|2023-01-22 00:00:00|
|  9|         4|       35.0|2023-02-25 00:00:00|
| 10|         5|       45.8|2023-01-11 00:00:00|
+---+----------+-----------+-------------------+

root
 |-- id: integer (nullable = true)
 |-- cliente_id: integer (nullable = true)
 |-- valor_total: double (nullable = true)
 |-- data: timestamp (nullable = true)

In [ ]:
from pyspark.sql.functions import col

clientes_lobao_df = clientes.filter(col("Nome") == "Lobão") # busca por nome
clientes_lobao_df.show()

+-----+--------------+--------------------+--------------------+
| Nome|      Telefone|            Endereco|               Email|
+-----+--------------+--------------------+--------------------+
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lobão|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
+-----+--------------+--------------------+--------------------+
only showing top 20 rows

In [ ]:
clientes_lobao_df = clientes.filter(col("Nome").like("%ma%")) # busca por nome like
clientes_lobao_df.show()

+----------+--------------+--------------------+--------------------+
|      Nome|      Telefone|            Endereco|               Email|
+----------+--------------+--------------------+--------------------+
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
|Lucas Lima|(21) 4567-8901| Rua JKL - 159 - ...| lucas.lima@email...|
+----------+--------------+--------------------+--------------------+
only showing top 20 rows

In [ ]:
pedidos_df_fittrado = pedidos_df.filter( (col("valor_total") > 100) ) # busca por maior
pedidos_df_fittrado.show()

pedidos_df_fittrado = pedidos_df.filter( (col("valor_total") > 100) & (col("valor_total") > 80) ) # busca por maior com e
pedidos_df_fittrado.show()

pedidos_df_fittrado = pedidos_df.filter( (col("valor_total") > 100) | (col("valor_total") > 10) ) # busca por maior com ou
pedidos_df_fittrado.show()

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  6|         1|      100.8|2023-02-02 00:00:00|
+---+----------+-----------+-------------------+

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  6|         1|      100.8|2023-02-02 00:00:00|
+---+----------+-----------+-------------------+

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  1|         1|       20.2|2023-02-07 00:00:00|
|  2|         2|       21.4|2022-12-07 00:00:00|
|  3|         3|       32.5|2020-05-01 00:00:00|
|  4|         4|      11.13|2023-02-12 00:00:00|
|  5|         5|      22.45|2023-07-08 00:00:00|
|  6|         1|      100.8|2023-02-02 00:00:00|
|  7|         2|       24.6|2021-05-07 00:00:00|
|  8|         3|       11.2|2023-01-22 00:00:00|
|  9|         4|       35.0|2023-02-25 00:00:00|
| 10|         5|       45.8|2023-01-11 00:00:00|
+---+----------+-----------+-------------------+

In [ ]:
from pyspark.sql.functions import col, date_format

pedidos_df_data1 = pedidos_df.filter(date_format(col("data"), "yyyy-MM") == "2023-01")
pedidos_df_data1.show()

pedidos_df_data_hora = pedidos_df.filter(col("data") > "2022-12-31 23:59:59")
pedidos_df_data_hora.show()

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  8|         3|       11.2|2023-01-22 00:00:00|
| 10|         5|       45.8|2023-01-11 00:00:00|
+---+----------+-----------+-------------------+

+---+----------+-----------+-------------------+
| id|cliente_id|valor_total|               data|
+---+----------+-----------+-------------------+
|  1|         1|       20.2|2023-02-07 00:00:00|
|  4|         4|      11.13|2023-02-12 00:00:00|
|  5|         5|      22.45|2023-07-08 00:00:00|
|  6|         1|      100.8|2023-02-02 00:00:00|
|  8|         3|       11.2|2023-01-22 00:00:00|
|  9|         4|       35.0|2023-02-25 00:00:00|
| 10|         5|       45.8|2023-01-11 00:00:00|
+---+----------+-----------+-------------------+

In [ ]:
! pip install faker # instala faker

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting faker
  Downloading Faker-17.4.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 52.5 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.8/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.4->faker) (1.15.0)
Installing collected packages: faker
Successfully installed faker-17.4.0

In [ ]:
# script para criar arquivos csv simulados

from faker import Faker
import csv
import random

# Inicializar o Faker com um idioma específico
fake = Faker("pt_BR")

# Gerar os dados dos clientes
clientes = []
for i in range(1, 101):
    nome = fake.name()
    email = fake.email()
    telefone = fake.phone_number()
    endereco = fake.address()
    clientes.append((i, nome, email, telefone, endereco))

# Escrever os dados dos clientes em um arquivo CSV
with open("clientes.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["id", "nome", "email", "telefone", "endereco"])
    writer.writerows(clientes)

# Gerar os dados dos pedidos
pedidos = []
for i in range(1, 201):
    cliente_id = random.randint(1, 100)
    descricao = fake.text(max_nb_chars=50)
    valor = round(random.uniform(10.0, 100.0), 2)
    pedidos.append((i, cliente_id, descricao, valor))

# Escrever os dados dos pedidos em um arquivo CSV
with open("pedidos.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["id", "cliente_id", "descricao", "valor"])
    writer.writerows(pedidos)

In [ ]:
# merge de 2 arquivos csv
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("merge_csv_files").getOrCreate()


clientes_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("clientes.csv")

pedidos_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("pedidos.csv")


merged_df = clientes_df.join(pedidos_df, clientes_df.id == pedidos_df.cliente_id, "inner")


merged_df.show()

+---+--------------------+--------------------+-------------------+--------------------+---+----------+--------------------+-----+
| id|                nome|               email|           telefone|            endereco| id|cliente_id|           descricao|valor|
+---+--------------------+--------------------+-------------------+--------------------+---+----------+--------------------+-----+
|  1|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|165|         1|  Ipsam quas dolore.|51.49|
|  1|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|159|         1|  Ut accusantium ex.|98.89|
|  1|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|129|         1|Id ipsum cum fuga...|44.41|
|  1|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53| 29|         1|Non aperiam possi...|22.04|
|  2|   Maria Luiza Jesus|  igor17@example.com|+55 (031) 1555 1960|Vila João Guilher...| 75|         2|Quidem earum atqu...|22.57|
|  3|    Dr. Heitor Souza|thalesalmeida@exa...|    (011) 8264-4959|Recanto Sabrina R...|173|         3|Ut sint neque nes...|88.89|
|  4|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias|112|         4|Sit qui iusto mag...|29.31|
|  4|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias| 95|         4|Animi dignissimos...|87.75|
|  6|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2|147|         6|Ipsum ullam amet ...| 76.0|
|  6|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2| 79|         6|Rerum odit saepe ...|71.63|
|  7|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|140|         7|Harum voluptatibu...|80.04|
|  7|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti| 67|         7|Fugiat libero lau...|32.08|
|  7|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti| 37|         7|Qui est harum ven...|86.69|
|  7|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti| 26|         7|Odio minima tenet...|21.48|
|  7|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti| 25|         7|Quasi architecto ...|99.56|
|  9|Ana Vitória Carvalho|guilhermeda-cunha...|   +55 84 0952 0707|Aeroporto de Nogu...| 49|         9|Veniam minus tota...|78.19|
| 10|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80| 47|        10|Corrupti officia ...|66.28|
| 10|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80|  2|        10|Magni quae mollit...|68.43|
| 11|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|188|        11|Quo vel sequi. Ut...|31.63|
| 11|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|124|        11|Aperiam at alias ...|55.41|
+---+--------------------+--------------------+-------------------+--------------------+---+----------+--------------------+-----+
only showing top 20 rows

In [ ]:
# cria arquivo merged.csv de um dataframe criado
merged_df = merged_df.drop("id")
merged_df.write.format("csv").mode("overwrite").option("header", "true").save("merged.csv")

In [ ]:
# merge de 2 arquivos csv
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("merge_csv_files").getOrCreate()


clientes_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("clientes.csv")

pedidos_df = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .load("pedidos.csv")


merged_df = clientes_df.join(pedidos_df, clientes_df.id == pedidos_df.cliente_id, "inner")

merged_df = merged_df.drop("id")

merged_df.show()

from pyspark.sql.functions import col

# Remove a coluna por indice
merged_df = merged_df.drop(col(merged_df.columns[5]))

# Exibir o DataFrame resultante
merged_df.show()

+--------------------+--------------------+-------------------+--------------------+----------+--------------------+-----+
|                nome|               email|           telefone|            endereco|cliente_id|           descricao|valor|
+--------------------+--------------------+-------------------+--------------------+----------+--------------------+-----+
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|  Ipsam quas dolore.|51.49|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|  Ut accusantium ex.|98.89|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|Id ipsum cum fuga...|44.41|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|Non aperiam possi...|22.04|
|   Maria Luiza Jesus|  igor17@example.com|+55 (031) 1555 1960|Vila João Guilher...|         2|Quidem earum atqu...|22.57|
|    Dr. Heitor Souza|thalesalmeida@exa...|    (011) 8264-4959|Recanto Sabrina R...|         3|Ut sint neque nes...|88.89|
|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias|         4|Sit qui iusto mag...|29.31|
|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias|         4|Animi dignissimos...|87.75|
|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2|         6|Ipsum ullam amet ...| 76.0|
|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2|         6|Rerum odit saepe ...|71.63|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|Harum voluptatibu...|80.04|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|Fugiat libero lau...|32.08|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|Qui est harum ven...|86.69|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|Odio minima tenet...|21.48|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|Quasi architecto ...|99.56|
|Ana Vitória Carvalho|guilhermeda-cunha...|   +55 84 0952 0707|Aeroporto de Nogu...|         9|Veniam minus tota...|78.19|
|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80|        10|Corrupti officia ...|66.28|
|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80|        10|Magni quae mollit...|68.43|
|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|        11|Quo vel sequi. Ut...|31.63|
|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|        11|Aperiam at alias ...|55.41|
+--------------------+--------------------+-------------------+--------------------+----------+--------------------+-----+
only showing top 20 rows

+--------------------+--------------------+-------------------+--------------------+----------+-----+
|                nome|               email|           telefone|            endereco|cliente_id|valor|
+--------------------+--------------------+-------------------+--------------------+----------+-----+
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|51.49|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|98.89|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|44.41|
|     Marina da Rocha|  joao90@example.net|   +55 11 5413-7709|   Parque da Luz, 53|         1|22.04|
|   Maria Luiza Jesus|  igor17@example.com|+55 (031) 1555 1960|Vila João Guilher...|         2|22.57|
|    Dr. Heitor Souza|thalesalmeida@exa...|    (011) 8264-4959|Recanto Sabrina R...|         3|88.89|
|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias|         4|29.31|
|      Alice da Rocha|  cpinto@example.net|    (041) 8675-3312|          Sítio Dias|         4|87.75|
|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2|         6| 76.0|
|  Davi Lucca Moreira|tpereira@example.net|    (084) 4374-8266| Rua Otávio Gomes, 2|         6|71.63|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|80.04|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|32.08|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|86.69|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|21.48|
|    João Lucas Pires|  nnunes@example.net|+55 (021) 8192 9144|     Vila Cavalcanti|         7|99.56|
|Ana Vitória Carvalho|guilhermeda-cunha...|   +55 84 0952 0707|Aeroporto de Nogu...|         9|78.19|
|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80|        10|66.28|
|        Clarice Lima|xrezende@example.net|       51 5117 6747|    Quadra Gomes, 80|        10|68.43|
|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|        11|31.63|
|        Murilo Porto|iribeiro@example.net|       71 7428 4884|Vale de Rodrigues, 5|        11|55.41|
+--------------------+--------------------+-------------------+--------------------+----------+-----+
only showing top 20 rows

In [ ]:
# adicionar uma coluna id em um dataframe

from pyspark.sql import SparkSession
from pyspark.sql.functions import row_number
from pyspark.sql.window import Window

# Criar uma sessão do Spark
spark = SparkSession.builder.appName("add_incremental_column").getOrCreate()

# Criar um DataFrame de exemplo
df = spark.createDataFrame([(25, "João"), (30, "Maria"), (40, "José")], ["idade", "nome"])

# Adicionar uma coluna "id" com valores incrementais
window = Window().orderBy('idade')
df = df.withColumn("id", row_number().over(window))

# Exibir o DataFrame resultante
df.show()

+-----+-----+---+
|idade| nome| id|
+-----+-----+---+
|   25| João|  1|
|   30|Maria|  2|
|   40| José|  3|
+-----+-----+---+

In [ ]:
from pyspark.sql import SparkSession

# Cria um DataFrame de exemplo
spark = SparkSession.builder.appName("rename_column").getOrCreate()
data = [("João", 25), ("Maria", 30), ("José", 40)]
df = spark.createDataFrame(data, ["nome", "idade"])

# Renomeia a coluna "idade" para "anos"
df = df.withColumnRenamed("idade", "anos")

# Exibe o DataFrame resultante
df.show()

+-----+----+
| nome|anos|
+-----+----+
| João|  25|
|Maria|  30|
| José|  40|
+-----+----+

In [ ]:
# mergiando 2 data frames

from pyspark.sql import SparkSession

# Cria uma sessão do Spark
spark = SparkSession.builder.appName("add_columns").getOrCreate()

# Cria nova lista de tuplas com os dados fictícios adicionais
data = [("João", 25, "joao@example.com", "123456789"),
            ("Maria", 30, "maria@example.com", "234567890"),
            ("José", 40, "jose@example.com", "345678901"),
            ("Ana", 22, "ana@example.com", "456789012"),
            ("Paulo", 35, "paulo@example.com", "567890123")]

# Cria um novo DataFrame com as colunas extras
df = spark.createDataFrame(data, ["nome", "idade", "email", "telefone"])

df.select('*').show() # mostra todos os dados
df.select('nome', 'idade').show() # mostra somete as colunas nome, idade

+-----+-----+-----------------+---------+
| nome|idade|            email| telefone|
+-----+-----+-----------------+---------+
| João|   25| joao@example.com|123456789|
|Maria|   30|maria@example.com|234567890|
| José|   40| jose@example.com|345678901|
|  Ana|   22|  ana@example.com|456789012|
|Paulo|   35|paulo@example.com|567890123|
+-----+-----+-----------------+---------+

+-----+-----+
| nome|idade|
+-----+-----+
| João|   25|
|Maria|   30|
| José|   40|
|  Ana|   22|
|Paulo|   35|
+-----+-----+

In [ ]:
# gera um data frame com dados fakes

from faker import Faker
from random import randint, uniform
from datetime import datetime, timedelta
from pyspark.sql import SparkSession

# Cria uma sessão do Spark
spark = SparkSession.builder.appName("data_simulator").getOrCreate()

# Define a quantidade de dados a serem gerados
num_rows = 1000

# Cria um objeto Faker para gerar dados fictícios
fake = Faker()

# Cria uma lista de tuplas com os dados fictícios
data = [(fake.name(), fake.word(), round(uniform(10, 100), 2),
         fake.date_time_between(start_date="-1y", end_date="now").strftime("%Y-%m-%d %H:%M:%S"))
        for _ in range(num_rows)]

# Cria um DataFrame com os dados fictícios
df = spark.createDataFrame(data, ["nome", "produto", "valor", "data_venda"])

# Exibe o DataFrame resultante
df.show()

+---------------+-----------+-----+-------------------+
|           nome|    produto|valor|         data_venda|
+---------------+-----------+-----+-------------------+
|Jesse Hernandez|     memory|67.61|2022-05-12 20:51:01|
|Jennifer Bryant|    subject|44.45|2022-04-05 22:08:16|
|   Paul Shelton|       huge|92.29|2022-11-07 10:19:40|
|Patrick Bennett|       wait|71.26|2022-05-08 16:39:42|
|  Lauren Barber|    surface|70.29|2022-08-12 21:30:02|
|Daniel Williams|      argue|80.57|2022-10-16 02:12:28|
|  Michelle Reed|       also|53.52|2022-10-18 07:28:17|
|     Tim Wilson|     across|12.17|2022-04-17 14:51:27|
|Allison Perkins| government|53.65|2022-11-10 16:05:27|
|  Travis Thomas|       drop| 55.0|2022-03-05 14:49:35|
|  Kenneth Rojas|     design|61.66|2022-10-10 11:44:57|
|Cynthia Bennett|    society| 50.1|2022-07-18 12:32:44|
|   Kerry Booker|        eat|40.39|2023-01-04 03:22:57|
|   Nathan Price|      these| 10.8|2022-11-04 19:14:57|
|    Amy Farrell|         ok|43.72|2022-11-10 19:07:22|
|   Jaime Miller|      money|34.47|2023-01-23 22:57:08|
|   Sharon White|       baby|87.69|2022-10-09 08:36:12|
|   Eddie Sutton|performance|56.88|2022-06-30 11:14:05|
|    Molly Bruce|       pull|22.25|2022-08-05 18:05:51|
| Nathan Stewart|      space|80.08|2022-06-09 04:10:42|
+---------------+-----------+-----+-------------------+
only showing top 20 rows

In [ ]:
# retorna o dataframe com uma coluna nova somente com o ano

from pyspark.sql.functions import year

# cria a coluna ano_venda a partir da coluna data_venda
df = df.withColumn("ano_venda", year("data_venda"))

# exibe o DataFrame resultante
df.show()

# mostra somente os campos, nome e ano_venda
df.select('nome', 'ano_venda').show()

+---------------+-----------+-----+-------------------+---------+
|           nome|    produto|valor|         data_venda|ano_venda|
+---------------+-----------+-----+-------------------+---------+
|Jesse Hernandez|     memory|67.61|2022-05-12 20:51:01|     2022|
|Jennifer Bryant|    subject|44.45|2022-04-05 22:08:16|     2022|
|   Paul Shelton|       huge|92.29|2022-11-07 10:19:40|     2022|
|Patrick Bennett|       wait|71.26|2022-05-08 16:39:42|     2022|
|  Lauren Barber|    surface|70.29|2022-08-12 21:30:02|     2022|
|Daniel Williams|      argue|80.57|2022-10-16 02:12:28|     2022|
|  Michelle Reed|       also|53.52|2022-10-18 07:28:17|     2022|
|     Tim Wilson|     across|12.17|2022-04-17 14:51:27|     2022|
|Allison Perkins| government|53.65|2022-11-10 16:05:27|     2022|
|  Travis Thomas|       drop| 55.0|2022-03-05 14:49:35|     2022|
|  Kenneth Rojas|     design|61.66|2022-10-10 11:44:57|     2022|
|Cynthia Bennett|    society| 50.1|2022-07-18 12:32:44|     2022|
|   Kerry Booker|        eat|40.39|2023-01-04 03:22:57|     2023|
|   Nathan Price|      these| 10.8|2022-11-04 19:14:57|     2022|
|    Amy Farrell|         ok|43.72|2022-11-10 19:07:22|     2022|
|   Jaime Miller|      money|34.47|2023-01-23 22:57:08|     2023|
|   Sharon White|       baby|87.69|2022-10-09 08:36:12|     2022|
|   Eddie Sutton|performance|56.88|2022-06-30 11:14:05|     2022|
|    Molly Bruce|       pull|22.25|2022-08-05 18:05:51|     2022|
| Nathan Stewart|      space|80.08|2022-06-09 04:10:42|     2022|
+---------------+-----------+-----+-------------------+---------+
only showing top 20 rows

+---------------+---------+
|           nome|ano_venda|
+---------------+---------+
|Jesse Hernandez|     2022|
|Jennifer Bryant|     2022|
|   Paul Shelton|     2022|
|Patrick Bennett|     2022|
|  Lauren Barber|     2022|
|Daniel Williams|     2022|
|  Michelle Reed|     2022|
|     Tim Wilson|     2022|
|Allison Perkins|     2022|
|  Travis Thomas|     2022|
|  Kenneth Rojas|     2022|
|Cynthia Bennett|     2022|
|   Kerry Booker|     2023|
|   Nathan Price|     2022|
|    Amy Farrell|     2022|
|   Jaime Miller|     2023|
|   Sharon White|     2022|
|   Eddie Sutton|     2022|
|    Molly Bruce|     2022|
| Nathan Stewart|     2022|
+---------------+---------+
only showing top 20 rows

In [ ]:
# mais exemplo usando select()

from pyspark.sql import SparkSession

# Criando uma SparkSession
spark = SparkSession.builder.appName("SelectExample").getOrCreate()

# Criando um dataframe df1
data1 = [("Alice", 25), ("Bob", 30), ("Charlie", 35)]
df1 = spark.createDataFrame(data1, ["Name", "Age"])

# Criando um dataframe df2
data2 = [("Alice", "female"), ("Bob", "male"), ("Charlie", "male")]
df2 = spark.createDataFrame(data2, ["Name", "Gender"])

# Selecionando campos de df1 e df2
selected = df1.select("Name", "Age").join(df2.select("Name", "Gender"), "Name")

# Mostrando o resultado
selected.show()

+-------+---+------+
|   Name|Age|Gender|
+-------+---+------+
|  Alice| 25|female|
|    Bob| 30|  male|
|Charlie| 35|  male|
+-------+---+------+

In [ ]:
# criando um dataframe e usando o sql para fazer buscas

from pyspark.sql import SparkSession

# Cria uma sessão do Spark
spark = SparkSession.builder.appName("sql_filter").getOrCreate()

# Cria um DataFrame com dados fictícios
data = [("João", 25), ("Maria", 30), ("José", 40), ("Ana", 22), ("Paulo", 35)]
df = spark.createDataFrame(data, ["nome", "idade"])

# Registra o DataFrame como uma tabela temporária
df.createOrReplaceTempView("pessoas")

# Executa uma consulta SQL para filtrar pessoas com idade maior que 30
resultado = spark.sql("SELECT nome, idade FROM pessoas WHERE idade > 30")

# Exibe o resultado
resultado.show()

+-----+-----+
| nome|idade|
+-----+-----+
| José|   40|
|Paulo|   35|
+-----+-----+

In [ ]:
# mergiando 2 data frames

from pyspark.sql import SparkSession

# Cria uma sessão do Spark
spark = SparkSession.builder.appName("add_columns").getOrCreate()

# Cria um DataFrame com dados fictícios
data = [("João", 25), ("Maria", 30), ("José", 40), ("Ana", 22), ("Paulo", 35)]
df = spark.createDataFrame(data, ["nome", "idade"])

# Cria uma nova lista de tuplas com os dados fictícios adicionais
new_data = [("João", 25, "joao@example.com", "123456789"),
            ("Maria", 30, "maria@example.com", "234567890"),
            ("José", 40, "jose@example.com", "345678901"),
            ("Ana", 22, "ana@example.com", "456789012"),
            ("Paulo", 35, "paulo@example.com", "567890123")]

# Cria um novo DataFrame com as colunas extras
new_df = spark.createDataFrame(new_data, ["nome", "idade", "email", "telefone"])

# Adiciona as colunas "email" e "telefone" ao DataFrame original
df = df.join(new_df, ["nome", "idade"], "outer")

# Exibe o DataFrame resultante
df.show()


# Registra o DataFrame como uma tabela temporária
df.createOrReplaceTempView("pessoas")


# Executa uma consulta SQL para filtrar pessoas com idade maior que 30
resultado = spark.sql("SELECT nome, idade FROM pessoas WHERE idade > 30")

resultado.show()


# Executa uma consulta SQL com todas as colunas para filtrar pessoas com idade maior que 30
resultado = spark.sql("SELECT * FROM pessoas WHERE idade > 30")

resultado.show()

+-----+-----+-----------------+---------+
| nome|idade|            email| telefone|
+-----+-----+-----------------+---------+
|  Ana|   22|  ana@example.com|456789012|
| José|   40| jose@example.com|345678901|
| João|   25| joao@example.com|123456789|
|Maria|   30|maria@example.com|234567890|
|Paulo|   35|paulo@example.com|567890123|
+-----+-----+-----------------+---------+

+-----+-----+
| nome|idade|
+-----+-----+
| José|   40|
|Paulo|   35|
+-----+-----+

+-----+-----+-----------------+---------+
| nome|idade|            email| telefone|
+-----+-----+-----------------+---------+
| José|   40| jose@example.com|345678901|
|Paulo|   35|paulo@example.com|567890123|
+-----+-----+-----------------+---------+

In [ ]:
# exemplo usando unnionAll

from pyspark.sql import SparkSession

# Inicializando a sessão do Spark
spark = SparkSession.builder.appName("Exemplo de unionAll").getOrCreate()

# Criando dois DataFrames
df1 = spark.createDataFrame([(1, "foo"), (2, "bar")], ["id", "valor"])
df2 = spark.createDataFrame([(3, "baz"), (4, "qux")], ["id", "valor"])

# Combinando os dois DataFrames usando unionAll
df_union = df1.unionAll(df2)

# Exibindo o resultado
df_union.show()

In [ ]:
# eexemplo union com sql

from pyspark.sql import SparkSession

# Inicializando a sessão do Spark
spark = SparkSession.builder.appName("Exemplo de unionAll").getOrCreate()

# Criando dois DataFrames
df1 = spark.createDataFrame([(1, "foo"), (2, "bar")], ["id", "valor"])
df2 = spark.createDataFrame([(3, "baz"), (4, "qux")], ["id", "valor"])

df1.createOrReplaceTempView('table1')
df2.createOrReplaceTempView('table2')

# Combinando os dois DataFrames usando unionAll
result = spark.sql("""
   SELECT * FROM table1 
   UNION ALL
   SELECT * FROM table2""")

# Exibindo o resultado
result.show()

In [ ]:
# Buscando informação por like

from pyspark.sql import SparkSession

# Cria uma sessão do Spark
spark = SparkSession.builder.appName("add_columns").getOrCreate()

# Cria uma nova lista de tuplas com os dados fictícios adicionais
new_data = [("João", 25, "joao@example.com", "123456789"),
            ("Maria", 30, "maria@example.com", "234567890"),
            ("José", 40, "jose@example.com", "345678901"),
            ("Ana", 22, "ana@example.com", "456789012"),
            ("Paulo", 35, "paulo@example.com", "567890123")]

# Cria um novo DataFrame com as colunas extras
new_df = spark.createDataFrame(new_data, ["nome", "idade", "email", "telefone"])

# Exibe o DataFrame resultante
new_df.show()


# Registra o DataFrame como uma tabela temporária
new_df.createOrReplaceTempView("pessoas")

resultado = spark.sql("SELECT * FROM pessoas WHERE nome like '%ari%'")

resultado.show()

+-----+-----+-----------------+---------+
| nome|idade|            email| telefone|
+-----+-----+-----------------+---------+
| João|   25| joao@example.com|123456789|
|Maria|   30|maria@example.com|234567890|
| José|   40| jose@example.com|345678901|
|  Ana|   22|  ana@example.com|456789012|
|Paulo|   35|paulo@example.com|567890123|
+-----+-----+-----------------+---------+

+-----+-----+-----------------+---------+
| nome|idade|            email| telefone|
+-----+-----+-----------------+---------+
|Maria|   30|maria@example.com|234567890|
+-----+-----+-----------------+---------+

In [ ]:
# fazendo select com múltiplas linhas 

from pyspark.sql import SparkSession

# Iniciando sessão do Spark
spark = SparkSession.builder.appName("Exemplo SQL Multilinha").getOrCreate()

# Criando um DataFrame de exemplo
df = spark.createDataFrame([(1, "Alice", 25), (2, "Bob", 30), (3, "Charlie", 35)], ["id", "nome", "idade"])

# Criando uma tabela temporária a partir do DataFrame
df.createOrReplaceTempView("pessoas")

# Executando uma query SQL com múltiplas linhas
query = """
    SELECT 
        nome, 
        idade 
    FROM 
        pessoas 
    WHERE 
        idade > 30
"""

resultado = spark.sql(query)

# Exibindo o resultado
resultado.show()

In [ ]:
# gerar um arquivo com empresas e anos com faturamento em python

import csv
from faker import Faker

# instancia o objeto Faker
fake = Faker()

# abre o arquivo para escrita
with open('empresas.csv', mode='w', newline='') as file:

    # define os nomes das colunas
    fieldnames = ['id', 'nome_empresa', 'estado_empresa', 'pais_empresa',
                  'valor_faturamento', 'mes_faturamento', 'ano_faturamento']

    # cria o objeto escritor do CSV
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # escreve a linha de cabeçalho com os nomes das colunas
    writer.writeheader()

    # itera 10.000 vezes para gerar os dados fictícios
    for i in range(10000):
        # gera os dados fictícios
        id = i
        nome_empresa = fake.company()
        estado_empresa = fake.state()
        pais_empresa = fake.country()
        valor_faturamento = fake.pyfloat(left_digits=6, right_digits=2, positive=True)
        mes_faturamento = fake.month()
        ano_faturamento = fake.year()

        # escreve uma nova linha no arquivo CSV com os dados fictícios
        writer.writerow({'id': id, 'nome_empresa': nome_empresa, 'estado_empresa': estado_empresa,
                         'pais_empresa': pais_empresa, 'valor_faturamento': valor_faturamento,
                         'mes_faturamento': mes_faturamento, 'ano_faturamento': ano_faturamento})

In [ ]:
from pyspark.sql import SparkSession

# Cria ou/e inicia uma sessão spark
spark = SparkSession.builder.master("local[*]").appName("Read CSV").getOrCreate() 

# Le arquivo csv
df = spark.read.csv("/content/empresas.csv", header=True, inferSchema=True)

df.createOrReplaceTempView("empresas")

resultado = spark.sql("SELECT * FROM empresas WHERE mes_faturamento = 1 and ano_faturamento = 2023")

resultado.show()

+----+----------------+--------------+--------------------+-----------------+---------------+---------------+
|  id|    nome_empresa|estado_empresa|        pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|
+----+----------------+--------------+--------------------+-----------------+---------------+---------------+
| 921|Gonzales-Cordova|        Nevada|      Norfolk Island|        377673.82|              1|           2023|
|1953|  Stewart-Nelson|        Kansas|Saint Kitts and N...|         930208.2|              1|           2023|
+----+----------------+--------------+--------------------+-----------------+---------------+---------------+

In [ ]:
from pyspark.sql import SparkSession

# Cria ou/e inicia uma sessão spark
spark = SparkSession.builder.master("local[*]").appName("Read CSV").getOrCreate() 

# Le arquivo csv
df = spark.read.csv("/content/empresas.csv", header=True, inferSchema=True)

df.createOrReplaceTempView("empresas")

resultado = spark.sql("SELECT * FROM empresas WHERE pais_empresa = 'Brasil' or pais_empresa = 'Brazil'")

resultado.show(truncate=False)

+----+-------------------------------+--------------+------------+-----------------+---------------+---------------+
|id  |nome_empresa                   |estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|
+----+-------------------------------+--------------+------------+-----------------+---------------+---------------+
|347 |Johnston-Flores                |Nevada        |Brazil      |382539.57        |8              |2017           |
|488 |Smith, Glenn and Anderson      |Oklahoma      |Brazil      |132308.7         |3              |1981           |
|727 |Pearson-Brown                  |North Carolina|Brazil      |614927.87        |2              |1990           |
|818 |Wilkinson Ltd                  |Delaware      |Brazil      |592875.98        |8              |1989           |
|929 |Day-Gray                       |Indiana       |Brazil      |345.5            |5              |2010           |
|1125|Cordova-Delgado                |Nebraska      |Brazil      |199653.24        |7              |2015           |
|1201|Paul PLC                       |New Hampshire |Brazil      |752474.35        |6              |1984           |
|1274|Thomas, Leblanc and Ruiz       |Kentucky      |Brazil      |112813.34        |4              |1974           |
|1347|Evans-Casey                    |Idaho         |Brazil      |807407.97        |11             |1998           |
|1536|Cook, Hunt and Farmer          |Rhode Island  |Brazil      |909601.0         |5              |2013           |
|1998|Williams, Blackburn and Barnett|Arizona       |Brazil      |650653.54        |4              |2020           |
|2710|Bailey, Perez and Moore        |Wisconsin     |Brazil      |17447.63         |11             |2014           |
|2752|Golden, Dunn and Rowe          |South Dakota  |Brazil      |717691.19        |12             |1976           |
|3237|Wright PLC                     |Massachusetts |Brazil      |148556.58        |5              |1999           |
|3368|Rocha, Herman and Richardson   |Washington    |Brazil      |834210.5         |1              |2000           |
|3648|Lopez LLC                      |South Carolina|Brazil      |485399.9         |4              |2010           |
|3697|Mcconnell Ltd                  |Missouri      |Brazil      |367523.78        |7              |2001           |
|4001|Jones Ltd                      |West Virginia |Brazil      |81863.65         |12             |1994           |
|4051|Meyer LLC                      |South Dakota  |Brazil      |843800.29        |3              |1988           |
|4131|Robinson, Brooks and Schwartz  |Hawaii        |Brazil      |915947.9         |2              |1980           |
+----+-------------------------------+--------------+------------+-----------------+---------------+---------------+
only showing top 20 rows

In [ ]:
! pip install unidecode

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting unidecode
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 KB 5.0 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.6

In [ ]:
# gera csv com estados reais brasileiros

import csv
from faker import Faker
from unidecode import unidecode

# instancia o objeto Faker
fake = Faker('pt_BR')

# abre o arquivo para escrita
with open('empresas.csv', mode='w', newline='') as file:

    # define os nomes das colunas
    fieldnames = ['id', 'nome_empresa', 'estado_empresa', 'pais_empresa',
                  'valor_faturamento', 'mes_faturamento', 'ano_faturamento']

    # cria o objeto escritor do CSV
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # escreve a linha de cabeçalho com os nomes das colunas
    writer.writeheader()

    # itera 10.000 vezes para gerar os dados fictícios
    for i in range(10000):
        # gera os dados fictícios
        id = i
        nome_empresa = fake.company()
        estado_empresa =  unidecode(", ".join(fake.estado()))
        pais_empresa = 'Brasil'
        valor_faturamento = fake.pyfloat(left_digits=6, right_digits=2, positive=True)
        mes_faturamento = fake.month()
        ano_faturamento = fake.year()

        # escreve uma nova linha no arquivo CSV com os dados fictícios
        writer.writerow({'id': id, 'nome_empresa': nome_empresa, 'estado_empresa': estado_empresa,
                         'pais_empresa': pais_empresa, 'valor_faturamento': valor_faturamento,
                         'mes_faturamento': mes_faturamento, 'ano_faturamento': ano_faturamento})


from pyspark.sql import SparkSession

# Cria ou/e inicia uma sessão spark
spark = SparkSession.builder.master("local[*]").appName("Read CSV").getOrCreate() 

# Le arquivo csv
df = spark.read.csv("/content/empresas.csv", header=True, inferSchema=True)

df.show()

+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
| id|        nome_empresa|      estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
|  0|             Correia|     MT, Mato Grosso|      Brasil|        504744.92|              1|           2015|
|  1|Aragão Rezende Ltda.|  ES, Espirito Santo|      Brasil|        920546.99|             11|           1976|
|  2|             Peixoto|     MT, Mato Grosso|      Brasil|        742950.62|              7|           1996|
|  3|da Cruz da Cunha ...|       TO, Tocantins|      Brasil|        978219.38|              3|           1987|
|  4| Barbosa Pereira S/A|RS, Rio Grande do...|      Brasil|         21270.94|              5|           2017|
|  5|          Costa S.A.|           GO, Goias|      Brasil|        313486.69|              9|           2005|
|  6|Oliveira da Luz - ME|      PE, Pernambuco|      Brasil|        848684.66|              8|           1980|
|  7|                Dias|           GO, Goias|      Brasil|        697989.74|              4|           2000|
|  8|               Silva|        MA, Maranhao|      Brasil|        347542.41|              2|           2022|
|  9|            Oliveira|           CE, Ceara|      Brasil|        760812.61|             11|           2015|
| 10|            da Costa|  SC, Santa Catarina|      Brasil|         19651.62|              3|           1981|
| 11|        da Conceição|           BA, Bahia|      Brasil|        100998.88|              5|           1982|
| 12|               Porto|RS, Rio Grande do...|      Brasil|         633182.9|              5|           2010|
| 13|            da Costa|           PI, Piaui|      Brasil|        231083.36|             10|           2019|
| 14|              Fogaça|           GO, Goias|      Brasil|        858131.57|              8|           1990|
| 15|              da Paz|           AP, Amapa|      Brasil|        122084.74|              2|           2006|
| 16|             Azevedo|         SE, Sergipe|      Brasil|        257707.44|              3|           2015|
| 17|              Campos|        MA, Maranhao|      Brasil|        147619.87|              8|           2022|
| 18|       das Neves S/A|RS, Rio Grande do...|      Brasil|        787191.23|              7|           1974|
| 19|          Porto S.A.|       SP, Sao Paulo|      Brasil|         871335.7|             11|           2015|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
only showing top 20 rows

In [ ]:
from pyspark.sql import SparkSession

# Cria ou/e inicia uma sessão spark
spark = SparkSession.builder.master("local[*]").appName("Read CSV").getOrCreate() 

# Le arquivo csv
df = spark.read.csv("/content/empresas.csv", header=True, inferSchema=True)

# Mostra dataframe
df.show()


# conta a quantidade de linhas
df.count()

In [ ]:
# split para gerar duas colunas separados por split(",")

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('SeparateStates').getOrCreate()

df = spark.createDataFrame([
    (0, "Correia", "MT, Mato Grosso", "Brasil", 504744.92, 1, 2015),
    (1, "Aragão Rezende Ltda.", "ES, Espirito Santo", "Brasil", 920546.99, 11, 1976),
    (2, "Peixoto", "MT, Mato Grosso", "Brasil", 742950.62, 7, 1996),
    (3, "da Cruz da Cunha LTDA", "TO, Tocantins", "Brasil", 978219.38, 3, 1987),
    (4, "Barbosa Pereira S/A", "RS, Rio Grande do Sul", "Brasil", 21270.94, 5, 2017),
    (5, "Costa S.A.", "GO, Goias", "Brasil", 313486.69, 9, 2005),
    (6, "Oliveira da Luz - ME", "PE, Pernambuco", "Brasil", 848684.66, 8, 1980),
    (7, "Dias", "GO, Goias", "Brasil", 697989.74, 4, 2000),
    (8, "Silva", "MA, Maranhao", "Brasil", 347542.41, 2, 2022),
    (9, "Oliveira", "CE, Ceara", "Brasil", 760812.61, 11, 2015),
    (10, "da Costa", "SC, Santa Catarina", "Brasil", 19651.62, 3, 1981),
    (11, "da Conceição", "BA, Bahia", "Brasil", 100998.88, 5, 1982),
    (12, "Porto", "RS, Rio Grande do Sul", "Brasil", 633182.9, 5, 2010),
    (13, "da Costa", "PI, Piaui", "Brasil", 231083.36, 10, 2019),
    (14, "Fogaça", "GO, Goias", "Brasil", 858131.57, 8, 1990),
    (15, "da Paz", "AP, Amapa", "Brasil", 122084.74, 2, 2006),
    (16, "Azevedo", "SE, Sergipe", "Brasil", 257707.44, 3, 2015),
    (17, "Campos", "MA, Maranhao", "Brasil", 147619.87, 8, 2022),
    (18, "das Neves S/A", "RS, Rio Grande do Sul", "Brasil", 787191.23, 7, 1974),
    (19, "Porto S.A.", "SP, Sao Paulo", "Brasil", 871335.7, 11, 2015)
], ['id', 'nome_empresa', 'estado_empresa', 'pais_empresa', 'valor_faturamento', 'mes_faturamento', 'ano_faturamento'])

df.show()

from pyspark.sql.functions import split

df = df.withColumn("estado", split(df["estado_empresa"], ",")[0])
df = df.withColumn("estado_empresa", split(df["estado_empresa"], ",")[1])
df.show()


from pyspark.sql.functions import concat_ws

df = df.withColumn("empresa_estado", concat_ws(" - ", df.estado_empresa, df.estado))
df.show()

+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
| id|        nome_empresa|      estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
|  0|             Correia|     MT, Mato Grosso|      Brasil|        504744.92|              1|           2015|
|  1|Aragão Rezende Ltda.|  ES, Espirito Santo|      Brasil|        920546.99|             11|           1976|
|  2|             Peixoto|     MT, Mato Grosso|      Brasil|        742950.62|              7|           1996|
|  3|da Cruz da Cunha ...|       TO, Tocantins|      Brasil|        978219.38|              3|           1987|
|  4| Barbosa Pereira S/A|RS, Rio Grande do...|      Brasil|         21270.94|              5|           2017|
|  5|          Costa S.A.|           GO, Goias|      Brasil|        313486.69|              9|           2005|
|  6|Oliveira da Luz - ME|      PE, Pernambuco|      Brasil|        848684.66|              8|           1980|
|  7|                Dias|           GO, Goias|      Brasil|        697989.74|              4|           2000|
|  8|               Silva|        MA, Maranhao|      Brasil|        347542.41|              2|           2022|
|  9|            Oliveira|           CE, Ceara|      Brasil|        760812.61|             11|           2015|
| 10|            da Costa|  SC, Santa Catarina|      Brasil|         19651.62|              3|           1981|
| 11|        da Conceição|           BA, Bahia|      Brasil|        100998.88|              5|           1982|
| 12|               Porto|RS, Rio Grande do...|      Brasil|         633182.9|              5|           2010|
| 13|            da Costa|           PI, Piaui|      Brasil|        231083.36|             10|           2019|
| 14|              Fogaça|           GO, Goias|      Brasil|        858131.57|              8|           1990|
| 15|              da Paz|           AP, Amapa|      Brasil|        122084.74|              2|           2006|
| 16|             Azevedo|         SE, Sergipe|      Brasil|        257707.44|              3|           2015|
| 17|              Campos|        MA, Maranhao|      Brasil|        147619.87|              8|           2022|
| 18|       das Neves S/A|RS, Rio Grande do...|      Brasil|        787191.23|              7|           1974|
| 19|          Porto S.A.|       SP, Sao Paulo|      Brasil|         871335.7|             11|           2015|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+

+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+
| id|        nome_empresa|    estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|estado|
+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+
|  0|             Correia|       Mato Grosso|      Brasil|        504744.92|              1|           2015|    MT|
|  1|Aragão Rezende Ltda.|    Espirito Santo|      Brasil|        920546.99|             11|           1976|    ES|
|  2|             Peixoto|       Mato Grosso|      Brasil|        742950.62|              7|           1996|    MT|
|  3|da Cruz da Cunha ...|         Tocantins|      Brasil|        978219.38|              3|           1987|    TO|
|  4| Barbosa Pereira S/A| Rio Grande do Sul|      Brasil|         21270.94|              5|           2017|    RS|
|  5|          Costa S.A.|             Goias|      Brasil|        313486.69|              9|           2005|    GO|
|  6|Oliveira da Luz - ME|        Pernambuco|      Brasil|        848684.66|              8|           1980|    PE|
|  7|                Dias|             Goias|      Brasil|        697989.74|              4|           2000|    GO|
|  8|               Silva|          Maranhao|      Brasil|        347542.41|              2|           2022|    MA|
|  9|            Oliveira|             Ceara|      Brasil|        760812.61|             11|           2015|    CE|
| 10|            da Costa|    Santa Catarina|      Brasil|         19651.62|              3|           1981|    SC|
| 11|        da Conceição|             Bahia|      Brasil|        100998.88|              5|           1982|    BA|
| 12|               Porto| Rio Grande do Sul|      Brasil|         633182.9|              5|           2010|    RS|
| 13|            da Costa|             Piaui|      Brasil|        231083.36|             10|           2019|    PI|
| 14|              Fogaça|             Goias|      Brasil|        858131.57|              8|           1990|    GO|
| 15|              da Paz|             Amapa|      Brasil|        122084.74|              2|           2006|    AP|
| 16|             Azevedo|           Sergipe|      Brasil|        257707.44|              3|           2015|    SE|
| 17|              Campos|          Maranhao|      Brasil|        147619.87|              8|           2022|    MA|
| 18|       das Neves S/A| Rio Grande do Sul|      Brasil|        787191.23|              7|           1974|    RS|
| 19|          Porto S.A.|         Sao Paulo|      Brasil|         871335.7|             11|           2015|    SP|
+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+

+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+--------------------+
| id|        nome_empresa|    estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|estado|      empresa_estado|
+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+--------------------+
|  0|             Correia|       Mato Grosso|      Brasil|        504744.92|              1|           2015|    MT|    Mato Grosso - MT|
|  1|Aragão Rezende Ltda.|    Espirito Santo|      Brasil|        920546.99|             11|           1976|    ES| Espirito Santo - ES|
|  2|             Peixoto|       Mato Grosso|      Brasil|        742950.62|              7|           1996|    MT|    Mato Grosso - MT|
|  3|da Cruz da Cunha ...|         Tocantins|      Brasil|        978219.38|              3|           1987|    TO|      Tocantins - TO|
|  4| Barbosa Pereira S/A| Rio Grande do Sul|      Brasil|         21270.94|              5|           2017|    RS| Rio Grande do Su...|
|  5|          Costa S.A.|             Goias|      Brasil|        313486.69|              9|           2005|    GO|          Goias - GO|
|  6|Oliveira da Luz - ME|        Pernambuco|      Brasil|        848684.66|              8|           1980|    PE|     Pernambuco - PE|
|  7|                Dias|             Goias|      Brasil|        697989.74|              4|           2000|    GO|          Goias - GO|
|  8|               Silva|          Maranhao|      Brasil|        347542.41|              2|           2022|    MA|       Maranhao - MA|
|  9|            Oliveira|             Ceara|      Brasil|        760812.61|             11|           2015|    CE|          Ceara - CE|
| 10|            da Costa|    Santa Catarina|      Brasil|         19651.62|              3|           1981|    SC| Santa Catarina - SC|
| 11|        da Conceição|             Bahia|      Brasil|        100998.88|              5|           1982|    BA|          Bahia - BA|
| 12|               Porto| Rio Grande do Sul|      Brasil|         633182.9|              5|           2010|    RS| Rio Grande do Su...|
| 13|            da Costa|             Piaui|      Brasil|        231083.36|             10|           2019|    PI|          Piaui - PI|
| 14|              Fogaça|             Goias|      Brasil|        858131.57|              8|           1990|    GO|          Goias - GO|
| 15|              da Paz|             Amapa|      Brasil|        122084.74|              2|           2006|    AP|          Amapa - AP|
| 16|             Azevedo|           Sergipe|      Brasil|        257707.44|              3|           2015|    SE|        Sergipe - SE|
| 17|              Campos|          Maranhao|      Brasil|        147619.87|              8|           2022|    MA|       Maranhao - MA|
| 18|       das Neves S/A| Rio Grande do Sul|      Brasil|        787191.23|              7|           1974|    RS| Rio Grande do Su...|
| 19|          Porto S.A.|         Sao Paulo|      Brasil|         871335.7|             11|           2015|    SP|      Sao Paulo - SP|
+---+--------------------+------------------+------------+-----------------+---------------+---------------+------+--------------------+

In [ ]:
# split para gerar duas colunas separados por split(",")

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('SeparateStates').getOrCreate()

df = spark.createDataFrame([
    (0, "Correia", "MT, Mato Grosso", "Brasil", 504744.92, 1, 2015),
    (1, "Aragão Rezende Ltda.", "ES, Espirito Santo", "Brasil", 920546.99, 11, 1976),
    (2, "Peixoto", "MT, Mato Grosso", "Brasil", 742950.62, 7, 1996),
    (3, "da Cruz da Cunha LTDA", "TO, Tocantins", "Brasil", 978219.38, 3, 1987),
    (4, "Barbosa Pereira S/A", "RS, Rio Grande do Sul", "Brasil", 21270.94, 5, 2017),
    (5, "Costa S.A.", "GO, Goias", "Brasil", 313486.69, 9, 2005),
    (6, "Oliveira da Luz - ME", "PE, Pernambuco", "Brasil", 848684.66, 8, 1980),
    (7, "Dias", "GO, Goias", "Brasil", 697989.74, 4, 2000),
    (8, "Silva", "MA, Maranhao", "Brasil", 347542.41, 2, 2022),
    (9, "Oliveira", "CE, Ceara", "Brasil", 760812.61, 11, 2015),
    (10, "da Costa", "SC, Santa Catarina", "Brasil", 19651.62, 3, 1981),
    (11, "da Conceição", "BA, Bahia", "Brasil", 100998.88, 5, 1982),
    (12, "Porto", "RS, Rio Grande do Sul", "Brasil", 633182.9, 5, 2010),
    (13, "da Costa", "PI, Piaui", "Brasil", 231083.36, 10, 2019),
    (14, "Fogaça", "GO, Goias", "Brasil", 858131.57, 8, 1990),
    (15, "da Paz", "AP, Amapa", "Brasil", 122084.74, 2, 2006),
    (16, "Azevedo", "SE, Sergipe", "Brasil", 257707.44, 3, 2015),
    (17, "Campos", "MA, Maranhao", "Brasil", 147619.87, 8, 2022),
    (18, "das Neves S/A", "RS, Rio Grande do Sul", "Brasil", 787191.23, 7, 1974),
    (19, "Porto S.A.", "SP, Sao Paulo", "Brasil", 871335.7, 11, 2015)
], ['id', 'nome_empresa', 'estado_empresa', 'pais_empresa', 'valor_faturamento', 'mes_faturamento', 'ano_faturamento'])

df.show()

from pyspark.sql.functions import lit

# adiciona uma nova coluna com valor 0
df = df.withColumn("nova_coluna", lit(0))
df.show()

+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
| id|        nome_empresa|      estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+
|  0|             Correia|     MT, Mato Grosso|      Brasil|        504744.92|              1|           2015|
|  1|Aragão Rezende Ltda.|  ES, Espirito Santo|      Brasil|        920546.99|             11|           1976|
|  2|             Peixoto|     MT, Mato Grosso|      Brasil|        742950.62|              7|           1996|
|  3|da Cruz da Cunha ...|       TO, Tocantins|      Brasil|        978219.38|              3|           1987|
|  4| Barbosa Pereira S/A|RS, Rio Grande do...|      Brasil|         21270.94|              5|           2017|
|  5|          Costa S.A.|           GO, Goias|      Brasil|        313486.69|              9|           2005|
|  6|Oliveira da Luz - ME|      PE, Pernambuco|      Brasil|        848684.66|              8|           1980|
|  7|                Dias|           GO, Goias|      Brasil|        697989.74|              4|           2000|
|  8|               Silva|        MA, Maranhao|      Brasil|        347542.41|              2|           2022|
|  9|            Oliveira|           CE, Ceara|      Brasil|        760812.61|             11|           2015|
| 10|            da Costa|  SC, Santa Catarina|      Brasil|         19651.62|              3|           1981|
| 11|        da Conceição|           BA, Bahia|      Brasil|        100998.88|              5|           1982|
| 12|               Porto|RS, Rio Grande do...|      Brasil|         633182.9|              5|           2010|
| 13|            da Costa|           PI, Piaui|      Brasil|        231083.36|             10|           2019|
| 14|              Fogaça|           GO, Goias|      Brasil|        858131.57|              8|           1990|
| 15|              da Paz|           AP, Amapa|      Brasil|        122084.74|              2|           2006|
| 16|             Azevedo|         SE, Sergipe|      Brasil|        257707.44|              3|           2015|
| 17|              Campos|        MA, Maranhao|      Brasil|        147619.87|              8|           2022|
| 18|       das Neves S/A|RS, Rio Grande do...|      Brasil|        787191.23|              7|           1974|
| 19|          Porto S.A.|       SP, Sao Paulo|      Brasil|         871335.7|             11|           2015|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+

+---+--------------------+--------------------+------------+-----------------+---------------+---------------+-----------+
| id|        nome_empresa|      estado_empresa|pais_empresa|valor_faturamento|mes_faturamento|ano_faturamento|nova_coluna|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+-----------+
|  0|             Correia|     MT, Mato Grosso|      Brasil|        504744.92|              1|           2015|          0|
|  1|Aragão Rezende Ltda.|  ES, Espirito Santo|      Brasil|        920546.99|             11|           1976|          0|
|  2|             Peixoto|     MT, Mato Grosso|      Brasil|        742950.62|              7|           1996|          0|
|  3|da Cruz da Cunha ...|       TO, Tocantins|      Brasil|        978219.38|              3|           1987|          0|
|  4| Barbosa Pereira S/A|RS, Rio Grande do...|      Brasil|         21270.94|              5|           2017|          0|
|  5|          Costa S.A.|           GO, Goias|      Brasil|        313486.69|              9|           2005|          0|
|  6|Oliveira da Luz - ME|      PE, Pernambuco|      Brasil|        848684.66|              8|           1980|          0|
|  7|                Dias|           GO, Goias|      Brasil|        697989.74|              4|           2000|          0|
|  8|               Silva|        MA, Maranhao|      Brasil|        347542.41|              2|           2022|          0|
|  9|            Oliveira|           CE, Ceara|      Brasil|        760812.61|             11|           2015|          0|
| 10|            da Costa|  SC, Santa Catarina|      Brasil|         19651.62|              3|           1981|          0|
| 11|        da Conceição|           BA, Bahia|      Brasil|        100998.88|              5|           1982|          0|
| 12|               Porto|RS, Rio Grande do...|      Brasil|         633182.9|              5|           2010|          0|
| 13|            da Costa|           PI, Piaui|      Brasil|        231083.36|             10|           2019|          0|
| 14|              Fogaça|           GO, Goias|      Brasil|        858131.57|              8|           1990|          0|
| 15|              da Paz|           AP, Amapa|      Brasil|        122084.74|              2|           2006|          0|
| 16|             Azevedo|         SE, Sergipe|      Brasil|        257707.44|              3|           2015|          0|
| 17|              Campos|        MA, Maranhao|      Brasil|        147619.87|              8|           2022|          0|
| 18|       das Neves S/A|RS, Rio Grande do...|      Brasil|        787191.23|              7|           1974|          0|
| 19|          Porto S.A.|       SP, Sao Paulo|      Brasil|         871335.7|             11|           2015|          0|
+---+--------------------+--------------------+------------+-----------------+---------------+---------------+-----------+

In [ ]:
# apaga as linhas que contém null

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()

# Remove rows with any NaN values
df_clean = df.dropna()

# Show the resulting dataframe
df_clean.show()

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  25|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  32|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-----+--------+-----------------+---+
| name|   phone|            email|age|
+-----+--------+-----------------+---+
|Alice|555-1234|alice@example.com| 25|
+-----+--------+-----------------+---+

In [ ]:
# remove as colunas que contem null

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()


from pyspark.sql.functions import col

# Get the list of column names
columns = df.columns

# Filter out columns that contain null values
non_null_columns = [col for col in columns if not df.filter(df[col].isNull()).count()]

# Drop columns that contain null values
df_clean = df.select(non_null_columns)

# Show the resulting dataframe
df_clean.show()

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  34|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  46|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-------+-------------------+
|   name|              email|
+-------+-------------------+
|  Alice|  alice@example.com|
|    Bob|    bob@example.com|
|Charlie|charlie@example.com|
|  David|  david@example.com|
+-------+-------------------+

In [ ]:
# substitui valor NaN por sem valor

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()

from pyspark.sql.functions import when

# Replace NaN values with "Sem valor"
df_clean = df.fillna({"phone": "Sem valor", "age": "Sem valor"})

# Alternative method to replace NaN values with "Sem valor"
df_clean = df.select([when(col(c).isNull(), "Sem valor").otherwise(col(c)).alias(c) for c in df.columns])

# Show the resulting dataframe
df_clean.show()

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  23|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  36|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-------+---------+-------------------+---------+
|   name|    phone|              email|      age|
+-------+---------+-------------------+---------+
|  Alice| 555-1234|  alice@example.com|       23|
|    Bob| 555-5678|    bob@example.com|Sem valor|
|Charlie|Sem valor|charlie@example.com|       36|
|  David| 555-9012|  david@example.com|Sem valor|
+-------+---------+-------------------+---------+

In [ ]:
# preenche 0 no valor NaN mais simpes

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()

df = df.na.fill(0) # para inteiros
df = df.na.fill('Sem valor') # para strings

df.show()

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  32|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  27|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-------+---------+-------------------+---+
|   name|    phone|              email|age|
+-------+---------+-------------------+---+
|  Alice| 555-1234|  alice@example.com| 32|
|    Bob| 555-5678|    bob@example.com|  0|
|Charlie|Sem valor|charlie@example.com| 27|
|  David| 555-9012|  david@example.com|  0|
+-------+---------+-------------------+---+

In [ ]:
# busca somente os dados que contém valor null

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()

from pyspark.sql.functions import col

# Filter rows containing null values
df_null = df.filter(col("name").isNull() | col("phone").isNull() | col("age").isNull())
df_null.show() # somente os null


df_null = df.filter(col("name").isNotNull() & col("phone").isNotNull() & col("age").isNotNull())
df_null.show() # somente os diferente de null


# Sort the dataframe by name
df_sorted = df.orderBy("name")
df_sorted.show() # mostra ordenado por nome

# Sort the dataframe by name in descending order
df_sorted = df.orderBy(col("name").desc())
# Show the resulting dataframe
df_sorted.show() # mostra ordenado por nome descendente


# Sort the dataframe by name in descending order
df_sorted = df.orderBy("name", ascending=False)
# Show the resulting dataframe
df_sorted.show() # mostra ordenado por nome descendente de outra forma


# Ordena por nome descendente e idade acendente
df_sorted = df.orderBy(["name", "age"], ascending=[False, True])
# Show the resulting dataframe
df_sorted.show() # mostra ordenado por nome descendente de outra forma com duas colunas

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  26|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-----+--------+-----------------+---+
| name|   phone|            email|age|
+-----+--------+-----------------+---+
|Alice|555-1234|alice@example.com| 26|
+-----+--------+-----------------+---+

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  26|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  David|555-9012|  david@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|    Bob|555-5678|    bob@example.com|null|
|  Alice|555-1234|  alice@example.com|  26|
+-------+--------+-------------------+----+

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  David|555-9012|  david@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|    Bob|555-5678|    bob@example.com|null|
|  Alice|555-1234|  alice@example.com|  26|
+-------+--------+-------------------+----+

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  David|555-9012|  david@example.com|null|
|Charlie|    null|charlie@example.com|  33|
|    Bob|555-5678|    bob@example.com|null|
|  Alice|555-1234|  alice@example.com|  26|
+-------+--------+-------------------+----+

In [ ]:
# filtro com where

from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
import random

# Create a SparkSession
spark = SparkSession.builder.appName("FakeData").getOrCreate()

# Define the schema for the dataframe
schema = StructType([
    StructField("name", StringType(), nullable=False),
    StructField("phone", StringType(), nullable=True),
    StructField("email", StringType(), nullable=False),
    StructField("age", IntegerType(), nullable=True)
])

# Define some fake data
names = ["Alice", "Bob", "Charlie", "David"]
phones = ["555-1234", "555-5678", None, "555-9012"]
emails = ["alice@example.com", "bob@example.com", "charlie@example.com", "david@example.com"]
ages = [random.randint(20, 50) if i % 2 == 0 else None for i in range(4)]

# Create the dataframe
data = list(zip(names, phones, emails, ages))
df = spark.createDataFrame(data, schema=schema)

df.show()

from pyspark.sql.functions import col

# Filter rows containing null values
df_filtro = df.where("name == 'Alice'")
df_filtro.show() # somente os null

+-------+--------+-------------------+----+
|   name|   phone|              email| age|
+-------+--------+-------------------+----+
|  Alice|555-1234|  alice@example.com|  31|
|    Bob|555-5678|    bob@example.com|null|
|Charlie|    null|charlie@example.com|  34|
|  David|555-9012|  david@example.com|null|
+-------+--------+-------------------+----+

+-----+--------+-----------------+---+
| name|   phone|            email|age|
+-----+--------+-----------------+---+
|Alice|555-1234|alice@example.com| 31|
+-----+--------+-----------------+---+

In [ ]:
# group by mosrtando total de vendas por estado

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

# criando a sessão Spark
spark = SparkSession.builder.appName('GroupBy').getOrCreate()

# criando o DataFrame com alguns dados de exemplo
data = [('João', 'SP', 2000),
        ('Maria', 'RJ', 1000),
        ('Pedro', 'SP', 500),
        ('Ana', 'MG', 800),
        ('Lucas', 'RJ', 300),
        ('Julia', 'MG', 600)]
colunas = ['nome', 'estado', 'vendas']
df = spark.createDataFrame(data, colunas)

# usando groupBy e count para contar as vendas por estado
vendas_por_estado = df.groupBy('estado').count()

# mostrando o resultado
vendas_por_estado.show()

+------+-----+
|estado|count|
+------+-----+
|    SP|    2|
|    RJ|    2|
|    MG|    2|
+------+-----+

In [ ]:
# usando groupby group_by

from pyspark.sql import SparkSession
from pyspark.sql.functions import sum

# Create a SparkSession
spark = SparkSession.builder.appName("CustomerOrders").getOrCreate()

# Define the schema for the dataframe
schema = "customer_id INT, order_id INT, order_total DOUBLE"

# Define some fake customer order data
data = [(1, 101, 20.0), (2, 102, 30.0), (1, 103, 10.0), (3, 104, 15.0), (2, 105, 25.0)]

# Create the dataframe
df = spark.createDataFrame(data, schema=schema)

df.show()

# Compute the total order value for each customer
df_agg = df.groupBy("customer_id").agg(sum("order_total").alias("total_order_value"))

# Show the resulting dataframe
df_agg.show()

+-----------+--------+-----------+
|customer_id|order_id|order_total|
+-----------+--------+-----------+
|          1|     101|       20.0|
|          2|     102|       30.0|
|          1|     103|       10.0|
|          3|     104|       15.0|
|          2|     105|       25.0|
+-----------+--------+-----------+

+-----------+-----------------+
|customer_id|total_order_value|
+-----------+-----------------+
|          1|             30.0|
|          2|             55.0|
|          3|             15.0|
+-----------+-----------------+

In [ ]:
# groupby por dois dataframes relacionados com a soma dos valores


from pyspark.sql import SparkSession
from pyspark.sql.functions import sum

# Create a SparkSession
spark = SparkSession.builder.appName("GroupByExample").getOrCreate()

# Define the schema for the customers dataframe
customers_schema = StructType([
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("name", StringType(), nullable=False),
    StructField("email", StringType(), nullable=False)
])

# Define the schema for the orders dataframe
orders_schema = StructType([
    StructField("order_id", IntegerType(), nullable=False),
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("order_total", DoubleType(), nullable=False)
])

# Define some fake data for the customers dataframe
customers_data = [
    (1, "Alice", "alice@example.com"),
    (2, "Bob", "bob@example.com"),
    (3, "Charlie", "charlie@example.com"),
    (4, "David", "david@example.com")
]

# Define some fake data for the orders dataframe
orders_data = [
    (1, 1, 100.0),
    (2, 1, 200.0),
    (3, 2, 150.0),
    (4, 2, 75.0),
    (5, 3, 50.0),
    (6, 3, 75.0),
    (7, 4, 300.0),
    (8, 4, 50.0)
]

# Create the dataframes
customers_df = spark.createDataFrame(customers_data, schema=customers_schema)
orders_df = spark.createDataFrame(orders_data, schema=orders_schema)

# Perform the join and groupby operation
result_df = orders_df.join(customers_df, "customer_id").groupBy("name").agg(sum("order_total").alias("total_order"))

# Show the result
result_df.show()

+-------+-----------+
|   name|total_order|
+-------+-----------+
|Charlie|      125.0|
|    Bob|      225.0|
|  Alice|      300.0|
|  David|      350.0|
+-------+-----------+

In [ ]:
# groupby por dois dataframes relacionados com a maior valor


from pyspark.sql import SparkSession
from pyspark.sql.functions import max

# Create a SparkSession
spark = SparkSession.builder.appName("GroupByExample").getOrCreate()

# Define the schema for the customers dataframe
customers_schema = StructType([
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("name", StringType(), nullable=False),
    StructField("email", StringType(), nullable=False)
])

# Define the schema for the orders dataframe
orders_schema = StructType([
    StructField("order_id", IntegerType(), nullable=False),
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("order_total", DoubleType(), nullable=False)
])

# Define some fake data for the customers dataframe
customers_data = [
    (1, "Alice", "alice@example.com"),
    (2, "Bob", "bob@example.com"),
    (3, "Charlie", "charlie@example.com"),
    (4, "David", "david@example.com")
]

# Define some fake data for the orders dataframe
orders_data = [
    (1, 1, 100.0),
    (2, 1, 200.0),
    (3, 2, 150.0),
    (4, 2, 75.0),
    (5, 3, 50.0),
    (6, 3, 75.0),
    (7, 4, 300.0),
    (8, 4, 50.0)
]

# Create the dataframes
customers_df = spark.createDataFrame(customers_data, schema=customers_schema)
orders_df = spark.createDataFrame(orders_data, schema=orders_schema)

# Perform the join and groupby operation
result_df = orders_df.join(customers_df, "customer_id").groupBy("name").agg(max("order_total").alias("total_order"))

# Show the result
result_df.show()

+-------+-----------+
|   name|total_order|
+-------+-----------+
|Charlie|       75.0|
|    Bob|      150.0|
|  Alice|      200.0|
|  David|      300.0|
+-------+-----------+

In [ ]:
# groupby por dois dataframes relacionados com a menor valor


from pyspark.sql import SparkSession
from pyspark.sql.functions import min

# Create a SparkSession
spark = SparkSession.builder.appName("GroupByExample").getOrCreate()

# Define the schema for the customers dataframe
customers_schema = StructType([
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("name", StringType(), nullable=False),
    StructField("email", StringType(), nullable=False)
])

# Define the schema for the orders dataframe
orders_schema = StructType([
    StructField("order_id", IntegerType(), nullable=False),
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("order_total", DoubleType(), nullable=False)
])

# Define some fake data for the customers dataframe
customers_data = [
    (1, "Alice", "alice@example.com"),
    (2, "Bob", "bob@example.com"),
    (3, "Charlie", "charlie@example.com"),
    (4, "David", "david@example.com")
]

# Define some fake data for the orders dataframe
orders_data = [
    (1, 1, 100.0),
    (2, 1, 200.0),
    (3, 2, 150.0),
    (4, 2, 75.0),
    (5, 3, 50.0),
    (6, 3, 75.0),
    (7, 4, 300.0),
    (8, 4, 50.0)
]

# Create the dataframes
customers_df = spark.createDataFrame(customers_data, schema=customers_schema)
orders_df = spark.createDataFrame(orders_data, schema=orders_schema)

# Perform the join and groupby operation
result_df = orders_df.join(customers_df, "customer_id").groupBy("name").agg(min("order_total").alias("total_order"))

# Show the result
result_df.show()

+-------+-----------+
|   name|total_order|
+-------+-----------+
|Charlie|       50.0|
|    Bob|       75.0|
|  Alice|      100.0|
|  David|       50.0|
+-------+-----------+

In [ ]:
# groupby por dois dataframes relacionados com a média do valor


from pyspark.sql import SparkSession
from pyspark.sql.functions import mean

# Create a SparkSession
spark = SparkSession.builder.appName("GroupByExample").getOrCreate()

# Define the schema for the customers dataframe
customers_schema = StructType([
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("name", StringType(), nullable=False),
    StructField("email", StringType(), nullable=False)
])

# Define the schema for the orders dataframe
orders_schema = StructType([
    StructField("order_id", IntegerType(), nullable=False),
    StructField("customer_id", IntegerType(), nullable=False),
    StructField("order_total", DoubleType(), nullable=False)
])

# Define some fake data for the customers dataframe
customers_data = [
    (1, "Alice", "alice@example.com"),
    (2, "Bob", "bob@example.com"),
    (3, "Charlie", "charlie@example.com"),
    (4, "David", "david@example.com")
]

# Define some fake data for the orders dataframe
orders_data = [
    (1, 1, 100.0),
    (2, 1, 200.0),
    (3, 2, 150.0),
    (4, 2, 75.0),
    (5, 3, 50.0),
    (6, 3, 75.0),
    (7, 4, 300.0),
    (8, 4, 50.0)
]

# Create the dataframes
customers_df = spark.createDataFrame(customers_data, schema=customers_schema)
orders_df = spark.createDataFrame(orders_data, schema=orders_schema)

# Perform the join and groupby operation
result_df = orders_df.join(customers_df, "customer_id").groupBy("name").agg(mean("order_total").alias("total_order"))

# Show the result
result_df.show()

+-------+-----------+
|   name|total_order|
+-------+-----------+
|Charlie|       62.5|
|    Bob|      112.5|
|  Alice|      150.0|
|  David|      175.0|
+-------+-----------+

In [ ]:
# gera média de matérias de alunos

from pyspark.sql import SparkSession
from pyspark.sql.functions import mean, expr

# cria uma sessão do Spark
spark = SparkSession.builder.appName("Alunos").getOrCreate()

# cria um schema para o dataframe
schema = "nome STRING, matematica FLOAT, portugues FLOAT, historia FLOAT"

# cria uma lista de tuplas com dados fictícios de alunos
dados = [("Alice", 8.5, 7.0, 9.5),
         ("Bob", 6.0, 6.5, 7.5),
         ("Charlie", 9.0, 9.5, 8.0),
         ("David", 7.5, 8.0, 7.0),
         ("Eve", 9.5, 9.0, 10.0)]

# cria o dataframe a partir dos dados e do schema
df = spark.createDataFrame(dados, schema)
df.show()

# cria uma nova coluna com a média das notas de cada aluno
colunas = df.columns[1:]
media_expr = expr("({}) / {}".format(" + ".join(colunas), len(colunas)))
df_com_media = df.withColumn("media", media_expr)

# mostra o resultado
df_com_media.show()

+-------+----------+---------+--------+
|   nome|matematica|portugues|historia|
+-------+----------+---------+--------+
|  Alice|       8.5|      7.0|     9.5|
|    Bob|       6.0|      6.5|     7.5|
|Charlie|       9.0|      9.5|     8.0|
|  David|       7.5|      8.0|     7.0|
|    Eve|       9.5|      9.0|    10.0|
+-------+----------+---------+--------+

+-------+----------+---------+--------+-----------------+
|   nome|matematica|portugues|historia|            media|
+-------+----------+---------+--------+-----------------+
|  Alice|       8.5|      7.0|     9.5|8.333333333333334|
|    Bob|       6.0|      6.5|     7.5|6.666666666666667|
|Charlie|       9.0|      9.5|     8.0|8.833333333333334|
|  David|       7.5|      8.0|     7.0|              7.5|
|    Eve|       9.5|      9.0|    10.0|              9.5|
+-------+----------+---------+--------+-----------------+

In [ ]:
# gera média de matérias de alunos arredondada

from pyspark.sql import SparkSession
from pyspark.sql.functions import mean, expr, round

# cria uma sessão do Spark
spark = SparkSession.builder.appName("Alunos").getOrCreate()

# cria um schema para o dataframe
schema = "nome STRING, matematica FLOAT, portugues FLOAT, historia FLOAT"

# cria uma lista de tuplas com dados fictícios de alunos
dados = [("Alice", 8.5, 7.0, 9.5),
         ("Bob", 6.0, 6.5, 7.5),
         ("Charlie", 9.0, 9.5, 8.0),
         ("David", 7.5, 8.0, 7.0),
         ("Eve", 9.5, 9.0, 10.0)]

# cria o dataframe a partir dos dados e do schema
df = spark.createDataFrame(dados, schema)
df.show()

# cria uma nova coluna com a média das notas de cada aluno
colunas = df.columns[1:]
media_expr = expr("round(({}) / {}, 2)".format(" + ".join(colunas), len(colunas)))
df_com_media = df.withColumn("media", media_expr)

# mostra o resultado
df_com_media.show()

+-------+----------+---------+--------+
|   nome|matematica|portugues|historia|
+-------+----------+---------+--------+
|  Alice|       8.5|      7.0|     9.5|
|    Bob|       6.0|      6.5|     7.5|
|Charlie|       9.0|      9.5|     8.0|
|  David|       7.5|      8.0|     7.0|
|    Eve|       9.5|      9.0|    10.0|
+-------+----------+---------+--------+

+-------+----------+---------+--------+-----+
|   nome|matematica|portugues|historia|media|
+-------+----------+---------+--------+-----+
|  Alice|       8.5|      7.0|     9.5| 8.33|
|    Bob|       6.0|      6.5|     7.5| 6.67|
|Charlie|       9.0|      9.5|     8.0| 8.83|
|  David|       7.5|      8.0|     7.0|  7.5|
|    Eve|       9.5|      9.0|    10.0|  9.5|
+-------+----------+---------+--------+-----+

No módulo pyspark.sql.functions do Spark, tanto a função avg() quanto a função mean() são utilizadas para calcular a média dos valores de uma coluna do DataFrame.

A diferença entre essas duas funções é que avg() é uma função de agregação, o que significa que ela é usada com groupBy() para calcular a média para cada grupo. Já mean() é uma função de coluna, que retorna a média dos valores de uma única coluna, sem a necessidade de agrupar por outras colunas.

Em resumo, a função avg() é usada para calcular a média por grupo, enquanto a função mean() é usada para calcular a média em toda a coluna.

In [ ]:
# Mostra a estatistica resumida dos itens do dataframe

from pyspark.sql import SparkSession

# Cria um DataFrame de exemplo
spark = SparkSession.builder.appName("rename_column").getOrCreate()
data = [("João", 25), ("Maria", 30), ("José", 40)]
df = spark.createDataFrame(data, ["nome", "idade"])

df.show()
df.summary().show()

# count = quantidade de registros
# mean = média das somas da coluna idade (25+35+30)/3
# stddev = desvio padrão entre os valores ( quando maior, maior a diferença entre a média, quando menor, menor a diferença )
# min = valor minimo da coluna age
# max = valor máximo da coluna age

# porcentagem entre os valores da coluna age
# 25%   27.5
# 50%   30.0
# 75%   32.5


# O desvio padrão (std) é uma medida de dispersão que indica o quão distante os valores estão da média. 
# Matematicamente, ele é a raiz quadrada da variância (var), que é a média dos quadrados das diferenças 
# entre cada valor e a média. O desvio padrão indica a quantidade de variação ou dispersão dos dados em relação à média. 
# Quanto maior o valor do desvio padrão, maior é a variabilidade dos dados em relação à média.

# No exemplo, o std é o desvio padrão da idade (age) dos clientes. 
# Ele foi calculado a partir da fórmula matemática std = sqrt(sum((xi - mean)^2) / (n - 1)), onde xi é cada valor da variável, 
# mean é a média da variável e n é o número de valores na variável. 
# O valor do std indica a variabilidade da idade dos clientes em relação à média.

+-----+-----+
| nome|idade|
+-----+-----+
| João|   25|
|Maria|   30|
| José|   40|
+-----+-----+

+-------+-----+------------------+
|summary| nome|             idade|
+-------+-----+------------------+
|  count|    3|                 3|
|   mean| null|31.666666666666668|
| stddev| null| 7.637626158259733|
|    min| José|                25|
|    25%| null|                25|
|    50%| null|                30|
|    75%| null|                40|
|    max|Maria|                40|
+-------+-----+------------------+

In [ ]:
# join
from pyspark.sql import SparkSession

# Cria uma sessão Spark
spark = SparkSession.builder.appName("Exemplo").getOrCreate()

# Cria os dataframes
df1 = spark.createDataFrame([(1, "A"), (2, "B"), (3, "C")], ["id", "coluna1"])
df2 = spark.createDataFrame([(1, "X"), (2, "Y"), (4, "Z")], ["id", "coluna2"])

# Realiza o inner join
df_join = df1.join(df2, ["id"], "inner") # podendo ser (inner, left, right, outer) igual no sql

# Exibe o resultado
df_join.show()

In [ ]:
#  Encerra Fecha sessão spark
spark.stop()

Trabalhando com RDDs no spark

In [ ]:
# Trabalhando com RDDs no spark

from pyspark import SparkContext

### para quando está em um cluster
# from pyspark import SparkContext, SparkConf
# conf = SparkConf().setAppName("Exemplo RDD").setMaster("local")
# sc = SparkContext(conf=conf)

sc = SparkContext()

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

rdd = sc.parallelize(arr)

display(rdd)

display( rdd.collect() ) # rdd.collect() = igual ao spark.show() mostra os valores
display( rdd.reduce(lambda x, y: x + y) ) # soma todos os valores do array, podem de forma distribuida, se eu tiver em um cluster ele vai dividir o calculo em memoria dos servidores
display( rdd.count() ) # conta a quantidade de registros


# transformar
rdd_trans = rdd.map(lambda x: x + 1) # soma + 1 em cada item do array
display( rdd_trans.collect() ) 


# filtro
rdd_filter = rdd.filter(lambda x: x > 5) # soma + 1 em cada item do array
display( rdd_filter.collect() ) 

sc.stop()

# O rdd é o que roda por trás do pyspark, sendo considerado low lavel API, já o pyspark é considerado hight level API

ParallelCollectionRDD[0] at readRDDFromFile at PythonRDD.scala:274

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

55

10

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

[6, 7, 8, 9, 10]

In [ ]:
# exemplo de transformação de dados usando RDD

from pyspark import SparkContext

# Cria um contexto Spark
sc = SparkContext("local", "RDD Transform Example")

# Cria um RDD com números de 1 a 5
numbers = sc.parallelize([1, 2, 3, 4, 5])

# Aplica a transformação filter() para manter apenas os números pares
even_numbers = numbers.filter(lambda x: x % 2 == 0)

# Aplica a transformação map() para multiplicar cada número par por 2
doubled_even_numbers = even_numbers.map(lambda x: x * 2)

# Realiza uma ação collect() para retornar uma lista com os elementos do RDD resultante
result = doubled_even_numbers.collect()

# Imprime o resultado
print(result)

# Finaliza o contexto Spark
sc.stop()

[4, 8]

In [ ]:
# Cria csv para usar no RDD

import csv

header = ['id', 'nome', 'telefone', 'email']
rows = [
    [1, 'João', '(11) 9999-1111', 'joao@email.com'],
    [2, 'Maria', '(21) 8888-2222', 'maria@email.com'],
    [3, 'Pedro', '(31) 7777-3333', 'pedro@email.com']
]

with open('exemplo.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(rows)

In [ ]:
# busando informação por nome utilizando rdd

from pyspark import SparkContext

sc = SparkContext("local", "Filter RDD Example")

data = sc.textFile("exemplo.csv")


filtered_data = data.filter(lambda x: x.split(",")[1].startswith("P"))

for line in filtered_data.collect():
    print(line)

sc.stop()

3,Pedro,(31) 7777-3333,pedro@email.com

**Trabalhando com Spark Streaming**

Streaming é quando vc pega informações de forma contínua, exemplo, com uso do kafka, RabbitMQ ou SQS

In [ ]:
!sudo apt install build-essential gcc make perl dkms curl tcl

Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version (4:9.3.0-1ubuntu2).
gcc set to manually installed.
make is already the newest version (4.2.1-1.2).
make set to manually installed.
tcl is already the newest version (8.6.9+1).
tcl set to manually installed.
build-essential is already the newest version (12.8ubuntu1.1).
curl is already the newest version (7.68.0-1ubuntu2.15).
dkms is already the newest version (2.8.1-5ubuntu2).
dkms set to manually installed.
perl is already the newest version (5.30.0-9ubuntu0.3).
perl set to manually installed.
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.

In [ ]:
!readlink -f $(which python3)

/usr/bin/python3.8

In [ ]:
# cria o websocket em python para dar a resposta em tempo real [producer.py] // Rodar de uma máquina python

import socket
import time

HOST = 'localhost'
PORT = 3000

s = socket.socket()
s.bind((HOST, PORT))
print(f'Aguardando conexão na porta: {PORT}')

s.listen(5)
conn, address = s.accept()

print (f'Recebendo solicitação de {address}')

# eviando mensagens do socket para o client
messages = [
  'Mensagem 1',
  'Mensagem 2',
  'Mensagem 3',
  'Mensagem 4'
]

for message in messages:
  message = bytes (message, 'utf-8')
  conn.send(message)
  time.sleep(4)

conn.close() # depois das mensagens enviadas, fecho o socket

Aguardando conexão na porta: 3000

In [ ]:
# Recebe solicitação do socket [consumer.py]

import socket
import time

HOST = 'localhost'
PORT = 3000

s = socket.socket()
s.connect((HOST, PORT))

# seu consomer recebe as mensagem até acabar
while True:
  data = s.recv(1024)
  dados = data.decode('utf-8')
  if(data == None or data == ""):
    break # fecha o looping quando não tiver mais mensagens
  print(dados)
  time.sleep(2)

In [ ]:
!lsof -i:3000 # descobre pid porta aberta

COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python3 116 root   43u  IPv4  40675      0t0  TCP localhost:3000 (LISTEN)

In [ ]:
!lsof -t -i:8080 # descobre somente pid porta aberta

7

In [ ]:
!kill -9 $(lsof -t -i:3000) # mata o pid

repo streaming kafka: 

https://github.com/torneseumprogramador/java-kafka-consumer

https://github.com/torneseumprogramador/java-kafka-producer


repo com testes em python

https://github.com/torneseumprogramador/python-streaming

In [ ]:
# codigo python para consumo de informações em fila do kafka

from kafka import KafkaConsumer

# Configurações do Kafka Consumer
bootstrap_servers = ['localhost:9092']
topic_name = 'meu-topico'
group_id = 'meu-grupo'

# Cria o Kafka Consumer
consumer = KafkaConsumer(
    topic_name,
    group_id=group_id,
    bootstrap_servers=bootstrap_servers,
    auto_offset_reset='earliest'  # Lê as mensagens desde o início do tópico
)

# Loop para consumir mensagens do tópico
for message in consumer:
    print(message.value.decode('utf-8'))

In [ ]:
!pip install kafka-python

In [ ]:
# codigo python para produzir dados para o kafka

from kafka import KafkaProducer
import json

# Configurações do Kafka Producer
bootstrap_servers = ['localhost:9092']
topic_name = 'meu-topico'

# Cria o Kafka Producer
producer = KafkaProducer(
    bootstrap_servers=bootstrap_servers,
    value_serializer=lambda v: json.dumps(v).encode('utf-8')  # Serializa os valores para JSON
)

# Produzindo mensagens para o tópico
for i in range(10):
    message = {'mensagem': f'Mensagem de teste {i}'}
    producer.send(topic_name, value=message)

# Flush para enviar mensagens pendentes
producer.flush()

In [ ]:
# exemplo do spark para consumir dados de um client kafka

from pyspark import SparkContext
from pyspark.streaming import StreamingContext
from pyspark.streaming.kafka import KafkaUtils
import json

# Configurações do Spark e do Kafka
sc = SparkContext(appName='Exemplo Spark Streaming com Kafka')
ssc = StreamingContext(sc, 1)  # Intervalo de 1 segundo
brokers = 'localhost:9092'
topic = 'meu-topico'
group_id = 'meu-grupo'

# Cria um stream do Kafka usando o KafkaUtils
kafka_stream = KafkaUtils.createStream(
    ssc, 
    brokers, 
    group_id, 
    {topic: 1}  # Lê o tópico com 1 thread
)

# Parse dos dados como JSON e contagem de palavras
parsed = kafka_stream.map(lambda v: json.loads(v[1]))
word_counts = parsed.flatMap(lambda line: line['mensagem'].split(' ')).map(lambda word: (word, 1)).reduceByKey(lambda a, b: a + b)

# Saída da contagem de palavras
word_counts.pprint()

# Inicia o streaming
ssc.start()
ssc.awaitTermination()